// Code generated by undoproxy-gen. DO NOT EDIT.

package gamestore

import "sync"

type undoKind uint8

const (
	undoKindGuildMembersMapPtrReplace undoKind = iota + 1
	undoKindGuildMembersMapEnsureNil
	undoKindGuildMembersMapKeySet
	undoKindHeroLevelScalarSet
	undoKindHeroSkillsMapPtrReplace
	undoKindHeroSkillsMapEnsureNil
	undoKindHeroSkillsMapKeySet
	undoKindItemIdScalarSet
	undoKindItemNameScalarSet
	undoKindMemberNameScalarSet
	undoKindMemberRankScalarSet
	undoKindPlayerGoldScalarSet
	undoKindPlayerWalletMapKeySet
	undoKindPlayerWalletMapEnsureNil
	undoKindPlayerItemsSliceTruncate
	undoKindPlayerItemsSliceSetAt
	undoKindPlayerItemsSliceRestore
	undoKindPlayerMainHeroPtrReplace
	undoKindPlayerHerosMapPtrReplace
	undoKindPlayerHerosMapEnsureNil
	undoKindPlayerHerosMapKeySet
	undoKindPlayerBagsMapSliceAppend
	undoKindPlayerBagsMapEnsureNil
	undoKindPlayerBagsMapSliceElemSet
	undoKindPlayerBagsMapSliceRestore
	undoKindPlayerBagsMapSlicePtrReplace
	undoKindPlayerBagsMapSlicePut
	undoKindPlayerStatsMapMapOuterDelete
	undoKindPlayerStatsMapMapInnerKeySet
	undoKindPlayerStatsMapEnsureNil
	undoKindPlayerStatsMapMapOuterRestore
	undoKindPlayerStatsMapMapInnerReplace
	undoKindSkillLevelScalarSet
)

type undoOp struct {
	kind      undoKind
	guild     *Guild
	hero      *Hero
	item      *Item
	member    *Member
	player    *Player
	skill     *Skill
	keyI32    int32
	keyI64    int64
	keyU64    uint64
	keyString string

	oldI32    int32
	oldI64    int64
	oldU64    uint64
	oldInt    int
	oldString string

	snapItem    []*Item
	innerMapOld map[string]int64

	had  bool
	had2 bool
}

// TxContext 单次请求作用域的 Undo 日志（单协程，无锁）。
//
// +k8s:deepcopy-gen=false
type TxContext struct {
	ops []undoOp
}

func (ctx *TxContext) push(op undoOp) {
	ctx.ops = append(ctx.ops, op)
}

// Reset 清空日志并复用底层切片。
func (ctx *TxContext) Reset() {
	for i := range ctx.ops {
		ctx.ops[i] = undoOp{}
	}
	ctx.ops = ctx.ops[:0]
}

var txPool = sync.Pool{
	New: func() any {
		return &TxContext{ops: make([]undoOp, 0, 16)}
	},
}

// Rollback 倒序执行所有逆操作。
func (ctx *TxContext) Rollback() {
	for i := len(ctx.ops) - 1; i >= 0; i-- {
		op := ctx.ops[i]
		switch op.kind {
		case undoKindGuildMembersMapPtrReplace:
			op.guild.Members[op.keyI32] = op.member
		case undoKindGuildMembersMapEnsureNil:
			op.guild.Members = nil
		case undoKindGuildMembersMapKeySet:
			if op.had {
				op.guild.Members[op.keyI32] = op.member
			} else {
				delete(op.guild.Members, op.keyI32)
			}
		case undoKindHeroLevelScalarSet:
			op.hero.Level = op.oldI32
		case undoKindHeroSkillsMapPtrReplace:
			op.hero.Skills[op.keyI32] = op.skill
		case undoKindHeroSkillsMapEnsureNil:
			op.hero.Skills = nil
		case undoKindHeroSkillsMapKeySet:
			if op.had {
				op.hero.Skills[op.keyI32] = op.skill
			} else {
				delete(op.hero.Skills, op.keyI32)
			}
		case undoKindItemIdScalarSet:
			op.item.Id = op.oldI64
		case undoKindItemNameScalarSet:
			op.item.Name = op.oldString
		case undoKindMemberNameScalarSet:
			op.member.Name = op.oldString
		case undoKindMemberRankScalarSet:
			op.member.Rank = op.oldI32
		case undoKindPlayerGoldScalarSet:
			op.player.Gold = op.oldI64
		case undoKindPlayerWalletMapKeySet:
			if op.had {
				op.player.Wallet[op.keyString] = op.oldI64
			} else {
				delete(op.player.Wallet, op.keyString)
			}
		case undoKindPlayerWalletMapEnsureNil:
			op.player.Wallet = nil
		case undoKindPlayerItemsSliceTruncate:
			op.player.Items = op.player.Items[:op.oldInt]
		case undoKindPlayerItemsSliceSetAt:
			op.player.Items[op.oldInt] = op.item
		case undoKindPlayerItemsSliceRestore:
			op.player.Items = append([]*Item(nil), op.snapItem...)
		case undoKindPlayerMainHeroPtrReplace:
			op.player.MainHero = op.hero
		case undoKindPlayerHerosMapPtrReplace:
			op.player.Heros[op.keyI32] = op.hero
		case undoKindPlayerHerosMapEnsureNil:
			op.player.Heros = nil
		case undoKindPlayerHerosMapKeySet:
			if op.had {
				op.player.Heros[op.keyI32] = op.hero
			} else {
				delete(op.player.Heros, op.keyI32)
			}
		case undoKindPlayerBagsMapSliceAppend:
			if op.had {
				op.player.Bags[op.keyI32] = op.snapItem[:op.oldInt]
			} else {
				delete(op.player.Bags, op.keyI32)
			}
		case undoKindPlayerBagsMapEnsureNil:
			op.player.Bags = nil
		case undoKindPlayerBagsMapSliceElemSet:
			op.player.Bags[op.keyI32][op.oldInt] = op.item
		case undoKindPlayerBagsMapSliceRestore:
			op.player.Bags[op.keyI32] = append([]*Item(nil), op.snapItem...)
		case undoKindPlayerBagsMapSlicePtrReplace:
			op.player.Bags[op.keyI32][i] = op.item
		case undoKindPlayerBagsMapSlicePut:
			if op.had {
				op.player.Bags[op.keyI32] = op.snapItem
			} else {
				delete(op.player.Bags, op.keyI32)
			}
		case undoKindPlayerStatsMapMapOuterDelete:
			delete(op.player.Stats, op.keyI32)
		case undoKindPlayerStatsMapMapInnerKeySet:
			inner := op.player.Stats[op.keyI32]
			if op.had {
				inner[op.keyString] = op.oldI64
			} else {
				delete(inner, op.keyString)
			}
		case undoKindPlayerStatsMapEnsureNil:
			op.player.Stats = nil
		case undoKindPlayerStatsMapMapOuterRestore:
			if op.had {
				op.player.Stats[op.keyI32] = op.innerMapOld
			} else {
				delete(op.player.Stats, op.keyI32)
			}
		case undoKindPlayerStatsMapMapInnerReplace:
			op.player.Stats[op.keyI32] = op.innerMapOld
		case undoKindSkillLevelScalarSet:
			op.skill.Level = op.oldI32
		}
	}
}

// CloneForWrite 返回 Guild 的可写浅拷贝。
func (g *Guild) CloneForWrite() *Guild {
	if g == nil {
		return nil
	}
	return &Guild{
		Members: g.Members,
	}
}

func (g *Guild) GetMemberForWrite(ctx *TxContext, k1 int32) *Member {
	if g.Members == nil {
		ctx.push(undoOp{kind: undoKindGuildMembersMapEnsureNil, guild: g})
		g.Members = make(map[int32]*Member)
	}
	old, ok := g.Members[k1]
	if !ok || old == nil {
		return nil
	}
	dirty := old.CloneForWrite()
	ctx.push(undoOp{kind: undoKindGuildMembersMapPtrReplace, guild: g, keyI32: k1, member: old})
	g.Members[k1] = dirty
	return dirty
}

func (g *Guild) PutMembers(ctx *TxContext, k1 int32, val *Member) {
	if g.Members == nil {
		ctx.push(undoOp{kind: undoKindGuildMembersMapEnsureNil, guild: g})
		g.Members = make(map[int32]*Member)
	}
	old, existed := g.Members[k1]
	if val != nil {
		val = val.CloneForWrite()
	}
	g.Members[k1] = val
	ctx.push(undoOp{kind: undoKindGuildMembersMapKeySet, guild: g, keyI32: k1, member: old, had: existed})
}

// CloneForWrite 返回 Hero 的可写浅拷贝。
func (h *Hero) CloneForWrite() *Hero {
	if h == nil {
		return nil
	}
	return &Hero{
		Level:  h.Level,
		Skills: h.Skills,
	}
}

func (h *Hero) PutLevel(ctx *TxContext, val int32) {
	old := h.Level
	ctx.push(undoOp{kind: undoKindHeroLevelScalarSet, hero: h, oldI32: old})
	h.Level = val
}

func (h *Hero) GetSkillForWrite(ctx *TxContext, k1 int32) *Skill {
	if h.Skills == nil {
		ctx.push(undoOp{kind: undoKindHeroSkillsMapEnsureNil, hero: h})
		h.Skills = make(map[int32]*Skill)
	}
	old, ok := h.Skills[k1]
	if !ok || old == nil {
		return nil
	}
	dirty := old.CloneForWrite()
	ctx.push(undoOp{kind: undoKindHeroSkillsMapPtrReplace, hero: h, keyI32: k1, skill: old})
	h.Skills[k1] = dirty
	return dirty
}

func (h *Hero) PutSkills(ctx *TxContext, k1 int32, val *Skill) {
	if h.Skills == nil {
		ctx.push(undoOp{kind: undoKindHeroSkillsMapEnsureNil, hero: h})
		h.Skills = make(map[int32]*Skill)
	}
	old, existed := h.Skills[k1]
	if val != nil {
		val = val.CloneForWrite()
	}
	h.Skills[k1] = val
	ctx.push(undoOp{kind: undoKindHeroSkillsMapKeySet, hero: h, keyI32: k1, skill: old, had: existed})
}

// CloneForWrite 返回 Item 的可写浅拷贝。
func (i *Item) CloneForWrite() *Item {
	if i == nil {
		return nil
	}
	return &Item{
		Id:   i.Id,
		Name: i.Name,
	}
}

func (i *Item) PutId(ctx *TxContext, val int64) {
	old := i.Id
	ctx.push(undoOp{kind: undoKindItemIdScalarSet, item: i, oldI64: old})
	i.Id = val
}

func (i *Item) PutName(ctx *TxContext, val string) {
	old := i.Name
	ctx.push(undoOp{kind: undoKindItemNameScalarSet, item: i, oldString: old})
	i.Name = val
}

// CloneForWrite 返回 Member 的可写浅拷贝。
func (m *Member) CloneForWrite() *Member {
	if m == nil {
		return nil
	}
	return &Member{
		Name: m.Name,
		Rank: m.Rank,
	}
}

func (m *Member) PutName(ctx *TxContext, val string) {
	old := m.Name
	ctx.push(undoOp{kind: undoKindMemberNameScalarSet, member: m, oldString: old})
	m.Name = val
}

func (m *Member) PutRank(ctx *TxContext, val int32) {
	old := m.Rank
	ctx.push(undoOp{kind: undoKindMemberRankScalarSet, member: m, oldI32: old})
	m.Rank = val
}

// CloneForWrite 返回 Player 的可写浅拷贝。
func (p *Player) CloneForWrite() *Player {
	if p == nil {
		return nil
	}
	return &Player{
		Gold:     p.Gold,
		Wallet:   p.Wallet,
		Items:    p.Items,
		MainHero: p.MainHero,
		Heros:    p.Heros,
		Bags:     p.Bags,
		Stats:    p.Stats,
	}
}

func (p *Player) PutGold(ctx *TxContext, val int64) {
	old := p.Gold
	ctx.push(undoOp{kind: undoKindPlayerGoldScalarSet, player: p, oldI64: old})
	p.Gold = val
}

func (p *Player) PutWallet(ctx *TxContext, k1 string, val int64) {
	if p.Wallet == nil {
		ctx.push(undoOp{kind: undoKindPlayerWalletMapEnsureNil, player: p})
		p.Wallet = make(map[string]int64)
	}
	old, existed := p.Wallet[k1]
	p.Wallet[k1] = val
	ctx.push(undoOp{kind: undoKindPlayerWalletMapKeySet, player: p, keyString: k1, oldI64: old, had: existed})
}

func (p *Player) AppendItems(ctx *TxContext, elem *Item) {
	oldLen := len(p.Items)
	p.Items = append(p.Items, elem)
	ctx.push(undoOp{kind: undoKindPlayerItemsSliceTruncate, player: p, oldInt: oldLen})
}

func (p *Player) SetItemsAt(ctx *TxContext, i int, elem *Item) {
	old := p.Items[i]
	ctx.push(undoOp{kind: undoKindPlayerItemsSliceSetAt, player: p, item: old, oldInt: i})
	p.Items[i] = elem
}

func (p *Player) RemoveItemsAt(ctx *TxContext, i int) {
	oldLen := len(p.Items)
	tail := append([]*Item(nil), p.Items...)
	p.Items = append(p.Items[:i], p.Items[i+1:]...)
	ctx.push(undoOp{kind: undoKindPlayerItemsSliceRestore, player: p, snapItem: tail, oldInt: oldLen})
}

func (p *Player) TruncateItems(ctx *TxContext, n int) {
	if n >= len(p.Items) {
		return
	}
	oldLen := len(p.Items)
	p.Items = p.Items[:n]
	ctx.push(undoOp{kind: undoKindPlayerItemsSliceTruncate, player: p, oldInt: oldLen})
}

func (p *Player) GetMainHeroForWrite(ctx *TxContext) *Hero {
	old := p.MainHero
	if old == nil {
		return nil
	}
	dirty := old.CloneForWrite()
	ctx.push(undoOp{kind: undoKindPlayerMainHeroPtrReplace, player: p, hero: old})
	p.MainHero = dirty
	return dirty
}

func (p *Player) GetHeroForWrite(ctx *TxContext, k1 int32) *Hero {
	if p.Heros == nil {
		ctx.push(undoOp{kind: undoKindPlayerHerosMapEnsureNil, player: p})
		p.Heros = make(map[int32]*Hero)
	}
	old, ok := p.Heros[k1]
	if !ok || old == nil {
		return nil
	}
	dirty := old.CloneForWrite()
	ctx.push(undoOp{kind: undoKindPlayerHerosMapPtrReplace, player: p, keyI32: k1, hero: old})
	p.Heros[k1] = dirty
	return dirty
}

func (p *Player) PutHeros(ctx *TxContext, k1 int32, val *Hero) {
	if p.Heros == nil {
		ctx.push(undoOp{kind: undoKindPlayerHerosMapEnsureNil, player: p})
		p.Heros = make(map[int32]*Hero)
	}
	old, existed := p.Heros[k1]
	if val != nil {
		val = val.CloneForWrite()
	}
	p.Heros[k1] = val
	ctx.push(undoOp{kind: undoKindPlayerHerosMapKeySet, player: p, keyI32: k1, hero: old, had: existed})
}

func (p *Player) AppendBagsAt(ctx *TxContext, k1 int32, elem *Item) {
	if p.Bags == nil {
		ctx.push(undoOp{kind: undoKindPlayerBagsMapEnsureNil, player: p})
		p.Bags = make(map[int32][]*Item)
	}
	prev, existed := p.Bags[k1]
	oldLen := len(prev)
	p.Bags[k1] = append(prev, elem)
	ctx.push(undoOp{kind: undoKindPlayerBagsMapSliceAppend, player: p, keyI32: k1, snapItem: prev, oldInt: oldLen, had: existed})
}

func (p *Player) SetBagsAt(ctx *TxContext, k1 int32, i int, elem *Item) {
	if p.Bags == nil {
		ctx.push(undoOp{kind: undoKindPlayerBagsMapEnsureNil, player: p})
		p.Bags = make(map[int32][]*Item)
	}
	oldElem := p.Bags[k1][i]
	ctx.push(undoOp{kind: undoKindPlayerBagsMapSliceElemSet, player: p, keyI32: k1, item: oldElem, oldInt: i})
	p.Bags[k1][i] = elem
}

func (p *Player) RemoveBagsAt(ctx *TxContext, k1 int32, i int) {
	if p.Bags == nil {
		ctx.push(undoOp{kind: undoKindPlayerBagsMapEnsureNil, player: p})
		p.Bags = make(map[int32][]*Item)
	}
	old, existed := p.Bags[k1]
	oldCopy := append([]*Item(nil), old...)
	p.Bags[k1] = append(old[:i], old[i+1:]...)
	ctx.push(undoOp{kind: undoKindPlayerBagsMapSliceRestore, player: p, keyI32: k1, snapItem: oldCopy, had: existed})
}

func (p *Player) TruncateBags(ctx *TxContext, k1 int32, n int) {
	if p.Bags == nil {
		ctx.push(undoOp{kind: undoKindPlayerBagsMapEnsureNil, player: p})
		p.Bags = make(map[int32][]*Item)
	}
	old, existed := p.Bags[k1]
	if n >= len(old) {
		return
	}
	oldCopy := append([]*Item(nil), old...)
	p.Bags[k1] = old[:n]
	ctx.push(undoOp{kind: undoKindPlayerBagsMapSliceRestore, player: p, keyI32: k1, snapItem: oldCopy, had: existed})
}

func (p *Player) GetItemAtForWrite(ctx *TxContext, k1 int32, i int) *Item {
	if p.Bags == nil {
		ctx.push(undoOp{kind: undoKindPlayerBagsMapEnsureNil, player: p})
		p.Bags = make(map[int32][]*Item)
	}
	old := p.Bags[k1][i]
	if old == nil {
		return nil
	}
	dirty := old.CloneForWrite()
	ctx.push(undoOp{kind: undoKindPlayerBagsMapSlicePtrReplace, player: p, keyI32: k1, item: old, oldInt: i})
	p.Bags[k1][i] = dirty
	return dirty
}

func (p *Player) PutBags(ctx *TxContext, k1 int32, val []*Item) {
	if p.Bags == nil {
		ctx.push(undoOp{kind: undoKindPlayerBagsMapEnsureNil, player: p})
		p.Bags = make(map[int32][]*Item)
	}
	old, existed := p.Bags[k1]
	oldCopy := append([]*Item(nil), old...)
	p.Bags[k1] = val
	ctx.push(undoOp{kind: undoKindPlayerBagsMapSlicePut, player: p, keyI32: k1, snapItem: oldCopy, had: existed})
}

func (p *Player) PutStats(ctx *TxContext, k1 int32, k2 string, val int64) {
	if p.Stats == nil {
		ctx.push(undoOp{kind: undoKindPlayerStatsMapEnsureNil, player: p})
		p.Stats = make(map[int32]map[string]int64)
	}
	inner, ok := p.Stats[k1]
	if !ok || inner == nil {
		ctx.push(undoOp{kind: undoKindPlayerStatsMapMapOuterDelete, player: p, had2: true})
		inner = make(map[string]int64)
		p.Stats[k1] = inner
	}
	old, existed := inner[k2]
	inner[k2] = val
	ctx.push(undoOp{kind: undoKindPlayerStatsMapMapInnerKeySet, player: p, keyI32: k1, keyString: k2, oldI64: old, had: existed})
}

func (p *Player) GetStatsMapForWrite(ctx *TxContext, k1 int32) map[string]int64 {
	if p.Stats == nil {
		ctx.push(undoOp{kind: undoKindPlayerStatsMapEnsureNil, player: p})
		p.Stats = make(map[int32]map[string]int64)
	}
	oldInner, existed := p.Stats[k1]
	if !existed || oldInner == nil {
		newInner := make(map[string]int64)
		ctx.push(undoOp{kind: undoKindPlayerStatsMapMapOuterRestore, player: p, keyI32: k1, had2: !existed})
		p.Stats[k1] = newInner
		return newInner
	}
	dirty := cloneStatsMapShallow(oldInner)
	ctx.push(undoOp{kind: undoKindPlayerStatsMapMapInnerReplace, player: p, keyI32: k1, innerMapOld: oldInner, had: true})
	p.Stats[k1] = dirty
	return dirty
}

func cloneStatsMapShallow(m map[string]int64) map[string]int64 {
	if m == nil {
		return nil
	}
	c := make(map[string]int64, len(m))
	for k, v := range m {
		c[k] = v
	}
	return c
}

// CloneForWrite 返回 Skill 的可写浅拷贝。
func (s *Skill) CloneForWrite() *Skill {
	if s == nil {
		return nil
	}
	return &Skill{
		Level: s.Level,
	}
}

func (s *Skill) PutLevel(ctx *TxContext, val int32) {
	old := s.Level
	ctx.push(undoOp{kind: undoKindSkillLevelScalarSet, skill: s, oldI32: old})
	s.Level = val
}
