// Code generated by undoproxy-gen (mode=v2). DO NOT EDIT.

package cow

import "sync"

type undoKindV2 uint8

const (
	undoKindPlayerLevelV2 undoKindV2 = iota + 1
	undoKindPlayerAssetsEnsureNilV2
	undoKindPlayerAssetsSetV2
	undoKindPlayerItemsTruncateV2
	undoKindPlayerItemsSetV2
	undoKindPlayerBagsEnsureNilV2
	undoKindPlayerBagsAppendAtKeyV2
	undoKindPlayerBagsSetAtKeyV2
	undoKindPlayerStatsEnsureNilV2
	undoKindPlayerStatsPutAtKeyV2
	undoKindPlayerStatsSetAtKeyV2
	undoKindPlayerCooldownsEnsureNilV2
	undoKindPlayerCooldownsSetAtKeyV2
	undoKindPlayerHerosEnsureNilV2
	undoKindPlayerHerosSetAtKeyV2
	undoKindPlayerMainHeroSetV2
	undoKindHeroLevelV2
)

type undoOpV2 struct {
	kind undoKindV2

	player *Player
	hero   *Hero

	keyI32    int32
	keyString string

	oldI32 int32
	oldI64 int64
	oldInt int

	tail     []*Item
	bagOld   []*Item
	statsOld map[string]int64
	cdOld    []int32

	had  bool
	had2 bool
}

// TxContextV2 实验性 Undo 日志（单协程，无锁）。
//
// 目标：并行验证结构化日志是否降低闭包分配。
//
// +k8s:deepcopy-gen=false
type TxContextV2 struct {
	ops []undoOpV2
}

func (ctx *TxContextV2) push(op undoOpV2) {
	ctx.ops = append(ctx.ops, op)
}

// Reset 清空日志并复用底层切片。
func (ctx *TxContextV2) Reset() {
	for i := range ctx.ops {
		ctx.ops[i] = undoOpV2{}
	}
	ctx.ops = ctx.ops[:0]
}

var txPoolV2 = sync.Pool{
	New: func() any {
		return &TxContextV2{ops: make([]undoOpV2, 0, 16)}
	},
}

// Rollback 倒序执行所有逆操作。
func (ctx *TxContextV2) Rollback() {
	for i := len(ctx.ops) - 1; i >= 0; i-- {
		op := ctx.ops[i]
		switch op.kind {
		case undoKindPlayerLevelV2:
			op.player.Level = op.oldI32
		case undoKindPlayerAssetsEnsureNilV2:
			op.player.Assets = nil
		case undoKindPlayerAssetsSetV2:
			if op.had {
				op.player.Assets[op.keyString] = op.oldI64
			} else {
				delete(op.player.Assets, op.keyString)
			}
		case undoKindPlayerItemsTruncateV2:
			op.player.Items = op.player.Items[:op.oldInt]
		case undoKindPlayerItemsSetV2:
			op.player.Items = append([]*Item(nil), op.tail...)
		case undoKindPlayerBagsEnsureNilV2:
			op.player.Bags = nil
		case undoKindPlayerBagsAppendAtKeyV2:
			if op.had {
				op.player.Bags[op.keyI32] = op.bagOld[:op.oldInt]
			} else {
				delete(op.player.Bags, op.keyI32)
			}
		case undoKindPlayerBagsSetAtKeyV2:
			if op.had {
				op.player.Bags[op.keyI32] = append([]*Item(nil), op.bagOld...)
			} else {
				delete(op.player.Bags, op.keyI32)
			}
		case undoKindPlayerStatsEnsureNilV2:
			op.player.Stats = nil
		case undoKindPlayerStatsPutAtKeyV2:
			inner := op.player.Stats[op.keyI32]
			if op.had {
				inner[op.keyString] = op.oldI64
			} else {
				delete(inner, op.keyString)
			}
			if op.had2 {
				delete(op.player.Stats, op.keyI32)
			}
		case undoKindPlayerStatsSetAtKeyV2:
			if op.had {
				op.player.Stats[op.keyI32] = cloneStatsMapShallowV2(op.statsOld)
			} else {
				delete(op.player.Stats, op.keyI32)
			}
		case undoKindPlayerCooldownsEnsureNilV2:
			op.player.Cooldowns = nil
		case undoKindPlayerCooldownsSetAtKeyV2:
			if op.had {
				op.player.Cooldowns[op.keyI32] = append([]int32(nil), op.cdOld...)
			} else {
				delete(op.player.Cooldowns, op.keyI32)
			}
		case undoKindPlayerHerosEnsureNilV2:
			op.player.Heros = nil
		case undoKindPlayerHerosSetAtKeyV2:
			if op.had {
				op.player.Heros[op.keyI32] = op.hero
			} else {
				delete(op.player.Heros, op.keyI32)
			}
		case undoKindPlayerMainHeroSetV2:
			op.player.MainHero = op.hero
		case undoKindHeroLevelV2:
			op.hero.Level = op.oldI32
		}
	}
}

func cloneStatsMapShallowV2(m map[string]int64) map[string]int64 {
	if m == nil {
		return nil
	}
	out := make(map[string]int64, len(m))
	for k, v := range m {
		out[k] = v
	}
	return out
}

// CloneForWriteV2 返回 Hero 的可写浅拷贝。
func (h *Hero) CloneForWriteV2() *Hero {
	if h == nil {
		return nil
	}
	return &Hero{
		HeroId: h.HeroId,
		Level:  h.Level,
		Skills: h.Skills,
	}
}

// PutLevelV2 写 Hero.Level 并记录结构化 Undo。
func (h *Hero) PutLevelV2(ctx *TxContextV2, val int32) {
	old := h.Level
	if old == val {
		return
	}
	ctx.push(undoOpV2{
		kind:   undoKindHeroLevelV2,
		hero:   h,
		oldI32: old,
	})
	h.Level = val
}

// PutAssetsV2 写 map 字段并记录结构化 Undo。
func (p *Player) PutAssetsV2(ctx *TxContextV2, k1 string, val int64) {
	if p.Assets == nil {
		ctx.push(undoOpV2{kind: undoKindPlayerAssetsEnsureNilV2, player: p})
		p.Assets = make(map[string]int64)
	}
	old, existed := p.Assets[k1]
	if existed && old == val {
		return
	}
	ctx.push(undoOpV2{
		kind:      undoKindPlayerAssetsSetV2,
		player:    p,
		keyString: k1,
		oldI64:    old,
		had:       existed,
	})
	p.Assets[k1] = val
}

// AppendItemsV2 append slice 并记录旧长度。
func (p *Player) AppendItemsV2(ctx *TxContextV2, elem *Item) {
	oldLen := len(p.Items)
	ctx.push(undoOpV2{kind: undoKindPlayerItemsTruncateV2, player: p, oldInt: oldLen})
	p.Items = append(p.Items, elem)
}

// RemoveItemsAtV2 删除指定下标元素并记录恢复快照。
func (p *Player) RemoveItemsAtV2(ctx *TxContextV2, i int) {
	oldLen := len(p.Items)
	tail := append([]*Item(nil), p.Items...)
	p.Items = append(p.Items[:i], p.Items[i+1:]...)
	ctx.push(undoOpV2{kind: undoKindPlayerItemsSetV2, player: p, oldInt: oldLen, tail: tail})
}

// TruncateItemsV2 截断切片并记录恢复快照。
func (p *Player) TruncateItemsV2(ctx *TxContextV2, n int) {
	if n >= len(p.Items) {
		return
	}
	oldLen := len(p.Items)
	tail := append([]*Item(nil), p.Items...)
	p.Items = p.Items[:n]
	ctx.push(undoOpV2{kind: undoKindPlayerItemsSetV2, player: p, oldInt: oldLen, tail: tail})
}

// GetMainHeroForWriteV2 返回可写 Hero 副本并记录结构化 Undo。
func (p *Player) GetMainHeroForWriteV2(ctx *TxContextV2) *Hero {
	old := p.MainHero
	if old == nil {
		return nil
	}
	dirty := old.CloneForWriteV2()
	ctx.push(undoOpV2{kind: undoKindPlayerMainHeroSetV2, player: p, hero: old})
	p.MainHero = dirty
	return dirty
}

// GetHeroForWriteV2 返回 map[k]*Hero 的可写副本，并记录 k1 对应旧状态。
func (p *Player) GetHeroForWriteV2(ctx *TxContextV2, k1 int32) *Hero {
	if p.Heros == nil {
		ctx.push(undoOpV2{kind: undoKindPlayerHerosEnsureNilV2, player: p})
		p.Heros = make(map[int32]*Hero)
	}
	old, existed := p.Heros[k1]
	if !existed || old == nil {
		return nil
	}
	dirty := old.CloneForWriteV2()
	ctx.push(undoOpV2{kind: undoKindPlayerHerosSetAtKeyV2, player: p, keyI32: k1, hero: old, had: existed})
	p.Heros[k1] = dirty
	return dirty
}

// PutHerosV2 写 map[k]*Hero，并记录 k1 对应旧状态。
func (p *Player) PutHerosV2(ctx *TxContextV2, k1 int32, val *Hero) {
	if p.Heros == nil {
		ctx.push(undoOpV2{kind: undoKindPlayerHerosEnsureNilV2, player: p})
		p.Heros = make(map[int32]*Hero)
	}
	old, existed := p.Heros[k1]
	if val != nil {
		val = val.CloneForWriteV2()
	}
	ctx.push(undoOpV2{kind: undoKindPlayerHerosSetAtKeyV2, player: p, keyI32: k1, hero: old, had: existed})
	p.Heros[k1] = val
}

// AppendBagsAtV2 追加 map[k][]*Item，并记录 k1 对应旧状态。
func (p *Player) AppendBagsAtV2(ctx *TxContextV2, k1 int32, elem *Item) {
	if p.Bags == nil {
		ctx.push(undoOpV2{kind: undoKindPlayerBagsEnsureNilV2, player: p})
		p.Bags = make(map[int32][]*Item)
	}
	old, existed := p.Bags[k1]
	next := append(old, elem)
	oldLen := len(old)
	ctx.push(undoOpV2{kind: undoKindPlayerBagsAppendAtKeyV2, player: p, keyI32: k1, bagOld: old, oldInt: oldLen, had: existed})
	p.Bags[k1] = next
}

// SetBagsAtV2 设置 map[k][]*Item 指定下标元素，并记录 k1 对应旧状态。
func (p *Player) SetBagsAtV2(ctx *TxContextV2, k1 int32, i int, elem *Item) {
	if p.Bags == nil {
		ctx.push(undoOpV2{kind: undoKindPlayerBagsEnsureNilV2, player: p})
		p.Bags = make(map[int32][]*Item)
	}
	old, existed := p.Bags[k1]
	oldCopy := append([]*Item(nil), old...)
	next := append([]*Item(nil), old...)
	next[i] = elem
	ctx.push(undoOpV2{kind: undoKindPlayerBagsSetAtKeyV2, player: p, keyI32: k1, bagOld: oldCopy, had: existed})
	p.Bags[k1] = next
}

// RemoveBagsAtV2 删除 map[k][]*Item 指定下标元素，并记录 k1 对应旧状态。
func (p *Player) RemoveBagsAtV2(ctx *TxContextV2, k1 int32, i int) {
	if p.Bags == nil {
		ctx.push(undoOpV2{kind: undoKindPlayerBagsEnsureNilV2, player: p})
		p.Bags = make(map[int32][]*Item)
	}
	old, existed := p.Bags[k1]
	oldCopy := append([]*Item(nil), old...)
	next := append([]*Item(nil), old...)
	next = append(next[:i], next[i+1:]...)
	ctx.push(undoOpV2{kind: undoKindPlayerBagsSetAtKeyV2, player: p, keyI32: k1, bagOld: oldCopy, had: existed})
	p.Bags[k1] = next
}

// TruncateBagsV2 截断 map[k][]*Item，并记录 k1 对应旧状态。
func (p *Player) TruncateBagsV2(ctx *TxContextV2, k1 int32, n int) {
	if p.Bags == nil {
		ctx.push(undoOpV2{kind: undoKindPlayerBagsEnsureNilV2, player: p})
		p.Bags = make(map[int32][]*Item)
	}
	old, existed := p.Bags[k1]
	if n >= len(old) {
		return
	}
	oldCopy := append([]*Item(nil), old...)
	next := append([]*Item(nil), old[:n]...)
	ctx.push(undoOpV2{kind: undoKindPlayerBagsSetAtKeyV2, player: p, keyI32: k1, bagOld: oldCopy, had: existed})
	p.Bags[k1] = next
}

// PutStatsV2 写 map[k]map[string]int64，并记录 k1 对应旧状态。
func (p *Player) PutStatsV2(ctx *TxContextV2, k1 int32, k2 string, val int64) {
	if p.Stats == nil {
		ctx.push(undoOpV2{kind: undoKindPlayerStatsEnsureNilV2, player: p})
		p.Stats = make(map[int32]map[string]int64)
	}
	inner, existed := p.Stats[k1]
	createdInner := false
	if !existed || inner == nil {
		inner = make(map[string]int64)
		p.Stats[k1] = inner
		createdInner = true
	}
	old, hadKey := inner[k2]
	if hadKey && old == val {
		if createdInner {
			delete(p.Stats, k1)
		}
		return
	}
	inner[k2] = val
	ctx.push(undoOpV2{kind: undoKindPlayerStatsPutAtKeyV2, player: p, keyI32: k1, keyString: k2, oldI64: old, had: hadKey, had2: createdInner})
}

// GetStatsMapForWriteV2 返回 map[k]string 的可写副本，并记录 k1 对应旧状态。
func (p *Player) GetStatsMapForWriteV2(ctx *TxContextV2, k1 int32) map[string]int64 {
	if p.Stats == nil {
		ctx.push(undoOpV2{kind: undoKindPlayerStatsEnsureNilV2, player: p})
		p.Stats = make(map[int32]map[string]int64)
	}
	oldInner, existed := p.Stats[k1]
	oldCopy := cloneStatsMapShallowV2(oldInner)
	next := cloneStatsMapShallowV2(oldInner)
	if next == nil {
		next = make(map[string]int64)
	}
	ctx.push(undoOpV2{kind: undoKindPlayerStatsSetAtKeyV2, player: p, keyI32: k1, statsOld: oldCopy, had: existed && oldInner != nil})
	p.Stats[k1] = next
	return next
}

// AppendCooldownsAtV2 追加 map[k][]int32，并记录 k1 对应旧状态。
func (p *Player) AppendCooldownsAtV2(ctx *TxContextV2, k1 int32, elem int32) {
	if p.Cooldowns == nil {
		ctx.push(undoOpV2{kind: undoKindPlayerCooldownsEnsureNilV2, player: p})
		p.Cooldowns = make(map[int32][]int32)
	}
	old, existed := p.Cooldowns[k1]
	next := append(old, elem)
	oldCopy := append([]int32(nil), old...)
	ctx.push(undoOpV2{kind: undoKindPlayerCooldownsSetAtKeyV2, player: p, keyI32: k1, cdOld: oldCopy, had: existed})
	p.Cooldowns[k1] = next
}

// SetCooldownsAtV2 设置 map[k][]int32 指定下标元素，并记录 k1 对应旧状态。
func (p *Player) SetCooldownsAtV2(ctx *TxContextV2, k1 int32, i int, elem int32) {
	if p.Cooldowns == nil {
		ctx.push(undoOpV2{kind: undoKindPlayerCooldownsEnsureNilV2, player: p})
		p.Cooldowns = make(map[int32][]int32)
	}
	old, existed := p.Cooldowns[k1]
	oldCopy := append([]int32(nil), old...)
	next := append([]int32(nil), old...)
	next[i] = elem
	ctx.push(undoOpV2{kind: undoKindPlayerCooldownsSetAtKeyV2, player: p, keyI32: k1, cdOld: oldCopy, had: existed})
	p.Cooldowns[k1] = next
}

// RemoveCooldownsAtV2 删除 map[k][]int32 指定下标元素，并记录 k1 对应旧状态。
func (p *Player) RemoveCooldownsAtV2(ctx *TxContextV2, k1 int32, i int) {
	if p.Cooldowns == nil {
		ctx.push(undoOpV2{kind: undoKindPlayerCooldownsEnsureNilV2, player: p})
		p.Cooldowns = make(map[int32][]int32)
	}
	old, existed := p.Cooldowns[k1]
	oldCopy := append([]int32(nil), old...)
	next := append([]int32(nil), old...)
	next = append(next[:i], next[i+1:]...)
	ctx.push(undoOpV2{kind: undoKindPlayerCooldownsSetAtKeyV2, player: p, keyI32: k1, cdOld: oldCopy, had: existed})
	p.Cooldowns[k1] = next
}

// TruncateCooldownsV2 截断 map[k][]int32，并记录 k1 对应旧状态。
func (p *Player) TruncateCooldownsV2(ctx *TxContextV2, k1 int32, n int) {
	if p.Cooldowns == nil {
		ctx.push(undoOpV2{kind: undoKindPlayerCooldownsEnsureNilV2, player: p})
		p.Cooldowns = make(map[int32][]int32)
	}
	old, existed := p.Cooldowns[k1]
	if n >= len(old) {
		return
	}
	oldCopy := append([]int32(nil), old...)
	next := append([]int32(nil), old[:n]...)
	ctx.push(undoOpV2{kind: undoKindPlayerCooldownsSetAtKeyV2, player: p, keyI32: k1, cdOld: oldCopy, had: existed})
	p.Cooldowns[k1] = next
}
