// Code generated by undoproxy-gen. DO NOT EDIT.

package cow

func (h *Hero) CloneForWrite() *Hero {
	if h == nil {
		return nil
	}
	return &Hero{
		HeroId: h.HeroId,
		Level:  h.Level,
		Skills: h.Skills,
	}
}

func (h *Hero) PutHeroId(ctx *TxContext, val int32) {
	old := h.HeroId
	ctx.AddUndo(func() { h.HeroId = old })
	h.HeroId = val
}

func (h *Hero) PutLevel(ctx *TxContext, val int32) {
	old := h.Level
	ctx.AddUndo(func() { h.Level = old })
	h.Level = val
}

func (h *Hero) GetSkillForWrite(ctx *TxContext, k1 int32) *Skill {
	if h.Skills == nil {
		ctx.AddUndo(func() { h.Skills = nil })
		h.Skills = make(map[int32]*Skill)
	}
	old, ok := h.Skills[k1]
	if !ok || old == nil {
		return nil
	}
	dirty := old.CloneForWrite()
	ctx.AddUndo(func() { h.Skills[k1] = old })
	h.Skills[k1] = dirty
	return dirty
}

func (h *Hero) PutSkills(ctx *TxContext, k1 int32, val *Skill) {
	if h.Skills == nil {
		ctx.AddUndo(func() { h.Skills = nil })
		h.Skills = make(map[int32]*Skill)
	}
	old, existed := h.Skills[k1]
	if val != nil {
		val = val.CloneForWrite()
	}
	h.Skills[k1] = val
	ctx.AddUndo(func() {
		if existed {
			h.Skills[k1] = old
		} else {
			delete(h.Skills, k1)
		}
	})
}

func (i *Item) CloneForWrite() *Item {
	if i == nil {
		return nil
	}
	return &Item{
		Id:    i.Id,
		Name:  i.Name,
		Extra: i.Extra,
	}
}

func (i *Item) PutId(ctx *TxContext, val int64) {
	old := i.Id
	ctx.AddUndo(func() { i.Id = old })
	i.Id = val
}

func (i *Item) PutName(ctx *TxContext, val string) {
	old := i.Name
	ctx.AddUndo(func() { i.Name = old })
	i.Name = val
}

func (i *Item) PutExtra(ctx *TxContext, val string) {
	old := i.Extra
	ctx.AddUndo(func() { i.Extra = old })
	i.Extra = val
}

func (m *Mail) CloneForWrite() *Mail {
	if m == nil {
		return nil
	}
	return &Mail{
		Id:      m.Id,
		Subject: m.Subject,
		Body:    m.Body,
	}
}

func (m *Mail) PutId(ctx *TxContext, val uint64) {
	old := m.Id
	ctx.AddUndo(func() { m.Id = old })
	m.Id = val
}

func (m *Mail) PutSubject(ctx *TxContext, val string) {
	old := m.Subject
	ctx.AddUndo(func() { m.Subject = old })
	m.Subject = val
}

func (m *Mail) PutBody(ctx *TxContext, val string) {
	old := m.Body
	ctx.AddUndo(func() { m.Body = old })
	m.Body = val
}

func (p *Player) CloneForWrite() *Player {
	if p == nil {
		return nil
	}
	return &Player{
		Uid:       p.Uid,
		Level:     p.Level,
		Assets:    p.Assets,
		Items:     p.Items,
		MainHero:  p.MainHero,
		Heros:     p.Heros,
		Bags:      p.Bags,
		Stats:     p.Stats,
		Cooldowns: p.Cooldowns,
		Mails:     p.Mails,
		Quests:    p.Quests,
	}
}

func (p *Player) PutUid(ctx *TxContext, val int64) {
	old := p.Uid
	ctx.AddUndo(func() { p.Uid = old })
	p.Uid = val
}

func (p *Player) PutLevel(ctx *TxContext, val int32) {
	old := p.Level
	ctx.AddUndo(func() { p.Level = old })
	p.Level = val
}

func (p *Player) PutAssets(ctx *TxContext, k1 string, val int64) {
	if p.Assets == nil {
		ctx.AddUndo(func() { p.Assets = nil })
		p.Assets = make(map[string]int64)
	}
	old, existed := p.Assets[k1]
	p.Assets[k1] = val
	ctx.AddUndo(func() {
		if existed {
			p.Assets[k1] = old
		} else {
			delete(p.Assets, k1)
		}
	})
}

func (p *Player) AppendItems(ctx *TxContext, elem *Item) {
	oldLen := len(p.Items)
	p.Items = append(p.Items, elem)
	ctx.AddUndo(func() { p.Items = p.Items[:oldLen] })
}

func (p *Player) SetItemsAt(ctx *TxContext, i int, elem *Item) {
	old := p.Items[i]
	ctx.AddUndo(func() { p.Items[i] = old })
	p.Items[i] = elem
}

func (p *Player) RemoveItemsAt(ctx *TxContext, i int) {
	old := p.Items[i]
	p.Items = append(p.Items[:i], p.Items[i+1:]...)
	ctx.AddUndo(func() { p.Items = append(p.Items[:i], append([]*Item{old}, p.Items[i:]...)...) })
}

func (p *Player) TruncateItems(ctx *TxContext, n int) {
	if n >= len(p.Items) {
		return
	}
	tail := append([]*Item(nil), p.Items[n:]...)
	p.Items = p.Items[:n]
	ctx.AddUndo(func() { p.Items = append(p.Items, tail...) })
}

func (p *Player) GetMainHeroForWrite(ctx *TxContext) *Hero {
	old := p.MainHero
	if old == nil {
		return nil
	}
	dirty := old.CloneForWrite()
	ctx.AddUndo(func() { p.MainHero = old })
	p.MainHero = dirty
	return dirty
}

func (p *Player) GetHeroForWrite(ctx *TxContext, k1 int32) *Hero {
	if p.Heros == nil {
		ctx.AddUndo(func() { p.Heros = nil })
		p.Heros = make(map[int32]*Hero)
	}
	old, ok := p.Heros[k1]
	if !ok || old == nil {
		return nil
	}
	dirty := old.CloneForWrite()
	ctx.AddUndo(func() { p.Heros[k1] = old })
	p.Heros[k1] = dirty
	return dirty
}

func (p *Player) PutHeros(ctx *TxContext, k1 int32, val *Hero) {
	if p.Heros == nil {
		ctx.AddUndo(func() { p.Heros = nil })
		p.Heros = make(map[int32]*Hero)
	}
	old, existed := p.Heros[k1]
	if val != nil {
		val = val.CloneForWrite()
	}
	p.Heros[k1] = val
	ctx.AddUndo(func() {
		if existed {
			p.Heros[k1] = old
		} else {
			delete(p.Heros, k1)
		}
	})
}

func (p *Player) AppendBagsAt(ctx *TxContext, k1 int32, elem *Item) {
	if p.Bags == nil {
		ctx.AddUndo(func() { p.Bags = nil })
		p.Bags = make(map[int32][]*Item)
	}
	prev, existed := p.Bags[k1]
	oldLen := len(prev)
	p.Bags[k1] = append(prev, elem)
	ctx.AddUndo(func() {
		if !existed {
			delete(p.Bags, k1)
		} else {
			p.Bags[k1] = prev[:oldLen]
		}
	})
}

func (p *Player) SetBagsAt(ctx *TxContext, k1 int32, i int, elem *Item) {
	if p.Bags == nil {
		ctx.AddUndo(func() { p.Bags = nil })
		p.Bags = make(map[int32][]*Item)
	}
	old := p.Bags[k1][i]
	ctx.AddUndo(func() { p.Bags[k1][i] = old })
	p.Bags[k1][i] = elem
}

func (p *Player) RemoveBagsAt(ctx *TxContext, k1 int32, i int) {
	if p.Bags == nil {
		ctx.AddUndo(func() { p.Bags = nil })
		p.Bags = make(map[int32][]*Item)
	}
	s := p.Bags[k1]
	old := s[i]
	p.Bags[k1] = append(s[:i], s[i+1:]...)
	ctx.AddUndo(func() { p.Bags[k1] = append(p.Bags[k1][:i], append([]*Item{old}, p.Bags[k1][i:]...)...) })
}

func (p *Player) TruncateBags(ctx *TxContext, k1 int32, n int) {
	if p.Bags == nil {
		ctx.AddUndo(func() { p.Bags = nil })
		p.Bags = make(map[int32][]*Item)
	}
	s := p.Bags[k1]
	if n >= len(s) {
		return
	}
	tail := append([]*Item(nil), s[n:]...)
	p.Bags[k1] = s[:n]
	ctx.AddUndo(func() { p.Bags[k1] = append(p.Bags[k1], tail...) })
}

func (p *Player) GetItemAtForWrite(ctx *TxContext, k1 int32, i int) *Item {
	if p.Bags == nil {
		ctx.AddUndo(func() { p.Bags = nil })
		p.Bags = make(map[int32][]*Item)
	}
	old := p.Bags[k1][i]
	if old == nil {
		return nil
	}
	dirty := old.CloneForWrite()
	ctx.AddUndo(func() { p.Bags[k1][i] = old })
	p.Bags[k1][i] = dirty
	return dirty
}

func (p *Player) PutBags(ctx *TxContext, k1 int32, val []*Item) {
	if p.Bags == nil {
		ctx.AddUndo(func() { p.Bags = nil })
		p.Bags = make(map[int32][]*Item)
	}
	old, existed := p.Bags[k1]
	p.Bags[k1] = val
	ctx.AddUndo(func() {
		if existed {
			p.Bags[k1] = old
		} else {
			delete(p.Bags, k1)
		}
	})
}

func (p *Player) PutStats(ctx *TxContext, k1 int32, k2 string, val int64) {
	if p.Stats == nil {
		ctx.AddUndo(func() { p.Stats = nil })
		p.Stats = make(map[int32]map[string]int64)
	}
	inner, ok := p.Stats[k1]
	if !ok || inner == nil {
		ctx.AddUndo(func() { delete(p.Stats, k1) })
		inner = make(map[string]int64)
		p.Stats[k1] = inner
	}
	old, existed := inner[k2]
	inner[k2] = val
	ctx.AddUndo(func() {
		if existed {
			inner[k2] = old
		} else {
			delete(inner, k2)
		}
	})
}

func (p *Player) GetStatsMapForWrite(ctx *TxContext, k1 int32) map[string]int64 {
	if p.Stats == nil {
		ctx.AddUndo(func() { p.Stats = nil })
		p.Stats = make(map[int32]map[string]int64)
	}
	oldInner, existed := p.Stats[k1]
	if !existed || oldInner == nil {
		newInner := make(map[string]int64)
		ctx.AddUndo(func() {
			if !existed {
				delete(p.Stats, k1)
			} else {
				p.Stats[k1] = oldInner
			}
		})
		p.Stats[k1] = newInner
		return newInner
	}
	dirty := cloneStatsMapShallow(oldInner)
	ctx.AddUndo(func() { p.Stats[k1] = oldInner })
	p.Stats[k1] = dirty
	return dirty
}

func cloneStatsMapShallow(m map[string]int64) map[string]int64 {
	if m == nil {
		return nil
	}
	c := make(map[string]int64, len(m))
	for k, v := range m {
		c[k] = v
	}
	return c
}

func (p *Player) AppendCooldownsAt(ctx *TxContext, k1 int32, elem int32) {
	if p.Cooldowns == nil {
		ctx.AddUndo(func() { p.Cooldowns = nil })
		p.Cooldowns = make(map[int32][]int32)
	}
	prev, existed := p.Cooldowns[k1]
	oldLen := len(prev)
	p.Cooldowns[k1] = append(prev, elem)
	ctx.AddUndo(func() {
		if !existed {
			delete(p.Cooldowns, k1)
		} else {
			p.Cooldowns[k1] = prev[:oldLen]
		}
	})
}

func (p *Player) SetCooldownsAt(ctx *TxContext, k1 int32, i int, elem int32) {
	if p.Cooldowns == nil {
		ctx.AddUndo(func() { p.Cooldowns = nil })
		p.Cooldowns = make(map[int32][]int32)
	}
	old := p.Cooldowns[k1][i]
	ctx.AddUndo(func() { p.Cooldowns[k1][i] = old })
	p.Cooldowns[k1][i] = elem
}

func (p *Player) RemoveCooldownsAt(ctx *TxContext, k1 int32, i int) {
	if p.Cooldowns == nil {
		ctx.AddUndo(func() { p.Cooldowns = nil })
		p.Cooldowns = make(map[int32][]int32)
	}
	s := p.Cooldowns[k1]
	old := s[i]
	p.Cooldowns[k1] = append(s[:i], s[i+1:]...)
	ctx.AddUndo(func() { p.Cooldowns[k1] = append(p.Cooldowns[k1][:i], append([]int32{old}, p.Cooldowns[k1][i:]...)...) })
}

func (p *Player) TruncateCooldowns(ctx *TxContext, k1 int32, n int) {
	if p.Cooldowns == nil {
		ctx.AddUndo(func() { p.Cooldowns = nil })
		p.Cooldowns = make(map[int32][]int32)
	}
	s := p.Cooldowns[k1]
	if n >= len(s) {
		return
	}
	tail := append([]int32(nil), s[n:]...)
	p.Cooldowns[k1] = s[:n]
	ctx.AddUndo(func() { p.Cooldowns[k1] = append(p.Cooldowns[k1], tail...) })
}

func (p *Player) PutCooldowns(ctx *TxContext, k1 int32, val []int32) {
	if p.Cooldowns == nil {
		ctx.AddUndo(func() { p.Cooldowns = nil })
		p.Cooldowns = make(map[int32][]int32)
	}
	old, existed := p.Cooldowns[k1]
	p.Cooldowns[k1] = val
	ctx.AddUndo(func() {
		if existed {
			p.Cooldowns[k1] = old
		} else {
			delete(p.Cooldowns, k1)
		}
	})
}

func (p *Player) GetMailForWrite(ctx *TxContext, k1 uint64) *Mail {
	if p.Mails == nil {
		ctx.AddUndo(func() { p.Mails = nil })
		p.Mails = make(map[uint64]*Mail)
	}
	old, ok := p.Mails[k1]
	if !ok || old == nil {
		return nil
	}
	dirty := old.CloneForWrite()
	ctx.AddUndo(func() { p.Mails[k1] = old })
	p.Mails[k1] = dirty
	return dirty
}

func (p *Player) PutMails(ctx *TxContext, k1 uint64, val *Mail) {
	if p.Mails == nil {
		ctx.AddUndo(func() { p.Mails = nil })
		p.Mails = make(map[uint64]*Mail)
	}
	old, existed := p.Mails[k1]
	if val != nil {
		val = val.CloneForWrite()
	}
	p.Mails[k1] = val
	ctx.AddUndo(func() {
		if existed {
			p.Mails[k1] = old
		} else {
			delete(p.Mails, k1)
		}
	})
}

func (p *Player) GetQuestForWrite(ctx *TxContext, k1 int32) *Quest {
	if p.Quests == nil {
		ctx.AddUndo(func() { p.Quests = nil })
		p.Quests = make(map[int32]*Quest)
	}
	old, ok := p.Quests[k1]
	if !ok || old == nil {
		return nil
	}
	dirty := old.CloneForWrite()
	ctx.AddUndo(func() { p.Quests[k1] = old })
	p.Quests[k1] = dirty
	return dirty
}

func (p *Player) PutQuests(ctx *TxContext, k1 int32, val *Quest) {
	if p.Quests == nil {
		ctx.AddUndo(func() { p.Quests = nil })
		p.Quests = make(map[int32]*Quest)
	}
	old, existed := p.Quests[k1]
	if val != nil {
		val = val.CloneForWrite()
	}
	p.Quests[k1] = val
	ctx.AddUndo(func() {
		if existed {
			p.Quests[k1] = old
		} else {
			delete(p.Quests, k1)
		}
	})
}

func (q *Quest) CloneForWrite() *Quest {
	if q == nil {
		return nil
	}
	return &Quest{
		Id:         q.Id,
		State:      q.State,
		Objectives: q.Objectives,
	}
}

func (q *Quest) PutId(ctx *TxContext, val int32) {
	old := q.Id
	ctx.AddUndo(func() { q.Id = old })
	q.Id = val
}

func (q *Quest) PutState(ctx *TxContext, val int32) {
	old := q.State
	ctx.AddUndo(func() { q.State = old })
	q.State = val
}

func (q *Quest) PutObjectives(ctx *TxContext, k1 int32, val int32) {
	if q.Objectives == nil {
		ctx.AddUndo(func() { q.Objectives = nil })
		q.Objectives = make(map[int32]int32)
	}
	old, existed := q.Objectives[k1]
	q.Objectives[k1] = val
	ctx.AddUndo(func() {
		if existed {
			q.Objectives[k1] = old
		} else {
			delete(q.Objectives, k1)
		}
	})
}

func (s *Skill) CloneForWrite() *Skill {
	if s == nil {
		return nil
	}
	return &Skill{
		SkillId: s.SkillId,
		Level:   s.Level,
	}
}

func (s *Skill) PutSkillId(ctx *TxContext, val int32) {
	old := s.SkillId
	ctx.AddUndo(func() { s.SkillId = old })
	s.SkillId = val
}

func (s *Skill) PutLevel(ctx *TxContext, val int32) {
	old := s.Level
	ctx.AddUndo(func() { s.Level = old })
	s.Level = val
}
