//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package cow

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Hero) DeepCopyInto(out *Hero) {
	*out = *in
	if in.Skills != nil {
		in, out := &in.Skills, &out.Skills
		*out = make(map[int32]*Skill, len(*in))
		for key, val := range *in {
			var outVal *Skill
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(Skill)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Hero.
func (in *Hero) DeepCopy() *Hero {
	if in == nil {
		return nil
	}
	out := new(Hero)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Item) DeepCopyInto(out *Item) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Item.
func (in *Item) DeepCopy() *Item {
	if in == nil {
		return nil
	}
	out := new(Item)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mail) DeepCopyInto(out *Mail) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mail.
func (in *Mail) DeepCopy() *Mail {
	if in == nil {
		return nil
	}
	out := new(Mail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Player) DeepCopyInto(out *Player) {
	*out = *in
	if in.Assets != nil {
		in, out := &in.Assets, &out.Assets
		*out = make(map[string]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]*Item, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Item)
				**out = **in
			}
		}
	}
	if in.MainHero != nil {
		in, out := &in.MainHero, &out.MainHero
		*out = new(Hero)
		(*in).DeepCopyInto(*out)
	}
	if in.Heros != nil {
		in, out := &in.Heros, &out.Heros
		*out = make(map[int32]*Hero, len(*in))
		for key, val := range *in {
			var outVal *Hero
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(Hero)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.Bags != nil {
		in, out := &in.Bags, &out.Bags
		*out = make(map[int32][]*Item, len(*in))
		for key, val := range *in {
			var outVal []*Item
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]*Item, len(*in))
				for i := range *in {
					if (*in)[i] != nil {
						in, out := &(*in)[i], &(*out)[i]
						*out = new(Item)
						**out = **in
					}
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.Stats != nil {
		in, out := &in.Stats, &out.Stats
		*out = make(map[int32]map[string]int64, len(*in))
		for key, val := range *in {
			var outVal map[string]int64
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(map[string]int64, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.Cooldowns != nil {
		in, out := &in.Cooldowns, &out.Cooldowns
		*out = make(map[int32][]int32, len(*in))
		for key, val := range *in {
			var outVal []int32
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]int32, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.Mails != nil {
		in, out := &in.Mails, &out.Mails
		*out = make(map[uint64]*Mail, len(*in))
		for key, val := range *in {
			var outVal *Mail
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(Mail)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Quests != nil {
		in, out := &in.Quests, &out.Quests
		*out = make(map[int32]*Quest, len(*in))
		for key, val := range *in {
			var outVal *Quest
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(Quest)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Player.
func (in *Player) DeepCopy() *Player {
	if in == nil {
		return nil
	}
	out := new(Player)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Quest) DeepCopyInto(out *Quest) {
	*out = *in
	if in.Objectives != nil {
		in, out := &in.Objectives, &out.Objectives
		*out = make(map[int32]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Quest.
func (in *Quest) DeepCopy() *Quest {
	if in == nil {
		return nil
	}
	out := new(Quest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Skill) DeepCopyInto(out *Skill) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Skill.
func (in *Skill) DeepCopy() *Skill {
	if in == nil {
		return nil
	}
	out := new(Skill)
	in.DeepCopyInto(out)
	return out
}
