// Code generated by undoproxy-gen. DO NOT EDIT.

package aftershop

import "sync"

type undoKind uint8

const (
	undoKindHeroLevelScalarSet undoKind = iota + 1
	undoKindItemIdScalarSet
	undoKindItemNameScalarSet
	undoKindPlayerGoldScalarSet
	undoKindPlayerWalletMapKeySet
	undoKindPlayerWalletMapEnsureNil
	undoKindPlayerItemsSliceTruncate
	undoKindPlayerItemsSliceSetAt
	undoKindPlayerItemsSliceRestore
	undoKindPlayerMainHeroPtrReplace
)

type undoOp struct {
	kind      undoKind
	hero      *Hero
	item      *Item
	player    *Player
	keyI32    int32
	keyI64    int64
	keyU64    uint64
	keyString string

	oldI32    int32
	oldI64    int64
	oldU64    uint64
	oldInt    int
	oldString string

	snapItem []*Item
	had      bool
	had2     bool
}

// TxContext 单次请求作用域的 Undo 日志（单协程，无锁）。
//
// +k8s:deepcopy-gen=false
type TxContext struct {
	ops []undoOp
}

func (ctx *TxContext) push(op undoOp) {
	ctx.ops = append(ctx.ops, op)
}

// Reset 清空日志并复用底层切片。
func (ctx *TxContext) Reset() {
	for i := range ctx.ops {
		ctx.ops[i] = undoOp{}
	}
	ctx.ops = ctx.ops[:0]
}

var txPool = sync.Pool{
	New: func() any {
		return &TxContext{ops: make([]undoOp, 0, 16)}
	},
}

// Rollback 倒序执行所有逆操作。
func (ctx *TxContext) Rollback() {
	for i := len(ctx.ops) - 1; i >= 0; i-- {
		op := ctx.ops[i]
		switch op.kind {
		case undoKindHeroLevelScalarSet:
			op.hero.Level = op.oldI32
		case undoKindItemIdScalarSet:
			op.item.Id = op.oldI64
		case undoKindItemNameScalarSet:
			op.item.Name = op.oldString
		case undoKindPlayerGoldScalarSet:
			op.player.Gold = op.oldI64
		case undoKindPlayerWalletMapKeySet:
			if op.had {
				op.player.Wallet[op.keyString] = op.oldI64
			} else {
				delete(op.player.Wallet, op.keyString)
			}
		case undoKindPlayerWalletMapEnsureNil:
			op.player.Wallet = nil
		case undoKindPlayerItemsSliceTruncate:
			op.player.Items = op.player.Items[:op.oldInt]
		case undoKindPlayerItemsSliceSetAt:
			op.player.Items[op.oldInt] = op.item
		case undoKindPlayerItemsSliceRestore:
			op.player.Items = append([]*Item(nil), op.snapItem...)
		case undoKindPlayerMainHeroPtrReplace:
			op.player.MainHero = op.hero
		}
	}
}

// CloneForWrite 返回 Hero 的可写浅拷贝。
func (h *Hero) CloneForWrite() *Hero {
	if h == nil {
		return nil
	}
	return &Hero{
		Level: h.Level,
	}
}

func (h *Hero) PutLevel(ctx *TxContext, val int32) {
	old := h.Level
	ctx.push(undoOp{kind: undoKindHeroLevelScalarSet, hero: h, oldI32: old})
	h.Level = val
}

// CloneForWrite 返回 Item 的可写浅拷贝。
func (i *Item) CloneForWrite() *Item {
	if i == nil {
		return nil
	}
	return &Item{
		Id:   i.Id,
		Name: i.Name,
	}
}

func (i *Item) PutId(ctx *TxContext, val int64) {
	old := i.Id
	ctx.push(undoOp{kind: undoKindItemIdScalarSet, item: i, oldI64: old})
	i.Id = val
}

func (i *Item) PutName(ctx *TxContext, val string) {
	old := i.Name
	ctx.push(undoOp{kind: undoKindItemNameScalarSet, item: i, oldString: old})
	i.Name = val
}

// CloneForWrite 返回 Player 的可写浅拷贝。
func (p *Player) CloneForWrite() *Player {
	if p == nil {
		return nil
	}
	return &Player{
		Gold:     p.Gold,
		Wallet:   p.Wallet,
		Items:    p.Items,
		MainHero: p.MainHero,
	}
}

func (p *Player) PutGold(ctx *TxContext, val int64) {
	old := p.Gold
	ctx.push(undoOp{kind: undoKindPlayerGoldScalarSet, player: p, oldI64: old})
	p.Gold = val
}

func (p *Player) PutWallet(ctx *TxContext, k1 string, val int64) {
	if p.Wallet == nil {
		ctx.push(undoOp{kind: undoKindPlayerWalletMapEnsureNil, player: p})
		p.Wallet = make(map[string]int64)
	}
	old, existed := p.Wallet[k1]
	p.Wallet[k1] = val
	ctx.push(undoOp{kind: undoKindPlayerWalletMapKeySet, player: p, keyString: k1, oldI64: old, had: existed})
}

func (p *Player) AppendItems(ctx *TxContext, elem *Item) {
	oldLen := len(p.Items)
	p.Items = append(p.Items, elem)
	ctx.push(undoOp{kind: undoKindPlayerItemsSliceTruncate, player: p, oldInt: oldLen})
}

func (p *Player) SetItemsAt(ctx *TxContext, i int, elem *Item) {
	old := p.Items[i]
	ctx.push(undoOp{kind: undoKindPlayerItemsSliceSetAt, player: p, item: old, oldInt: i})
	p.Items[i] = elem
}

func (p *Player) RemoveItemsAt(ctx *TxContext, i int) {
	oldLen := len(p.Items)
	tail := append([]*Item(nil), p.Items...)
	p.Items = append(p.Items[:i], p.Items[i+1:]...)
	ctx.push(undoOp{kind: undoKindPlayerItemsSliceRestore, player: p, snapItem: tail, oldInt: oldLen})
}

func (p *Player) TruncateItems(ctx *TxContext, n int) {
	if n >= len(p.Items) {
		return
	}
	oldLen := len(p.Items)
	p.Items = p.Items[:n]
	ctx.push(undoOp{kind: undoKindPlayerItemsSliceTruncate, player: p, oldInt: oldLen})
}

func (p *Player) GetMainHeroForWrite(ctx *TxContext) *Hero {
	old := p.MainHero
	if old == nil {
		return nil
	}
	dirty := old.CloneForWrite()
	ctx.push(undoOp{kind: undoKindPlayerMainHeroPtrReplace, player: p, hero: old})
	p.MainHero = dirty
	return dirty
}
