package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"

	"github.com/huangyuCN/cow/internal/cowgen"
)

func emitV2FromGraph(output, pkgName string, g *cowgen.Graph) error {
	var b bytes.Buffer
	b.WriteString("// Code generated by undoproxy-gen (mode=v2). DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", pkgName))
	b.WriteString("import \"sync\"\n\n")
	emitV2Runtime(&b)
	for _, sp := range g.Structs {
		switch sp.Name {
		case "Hero":
			emitCloneV2(&b, sp)
			emitHeroMethodsV2(&b, sp)
		case "Player":
			emitPlayerMethodsV2(&b, sp)
		}
	}
	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("format v2 graph: %w", err)
	}
	return os.WriteFile(output, formatted, 0o644)
}

func emitCloneV2(b *bytes.Buffer, sp *cowgen.StructPlan) {
	r := cowgen.RecvIdent(sp.Name)
	fmt.Fprintf(b, "// CloneForWriteV2 返回 %s 的可写浅拷贝。\n", sp.Name)
	fmt.Fprintf(b, "func (%s *%s) CloneForWriteV2() *%s {\n", r, sp.Name, sp.Name)
	fmt.Fprintf(b, "\tif %s == nil {\n\t\treturn nil\n\t}\n", r)
	fmt.Fprintf(b, "\treturn &%s{\n", sp.Name)
	st := sp.Struct
	for i := 0; i < st.NumFields(); i++ {
		f := st.Field(i)
		if !f.Exported() {
			continue
		}
		fmt.Fprintf(b, "\t\t%s: %s.%s,\n", f.Name(), r, f.Name())
	}
	b.WriteString("\t}\n}\n\n")
}

func emitHeroMethodsV2(b *bytes.Buffer, sp *cowgen.StructPlan) {
	r := cowgen.RecvIdent(sp.Name)
	for _, plan := range sp.Plans {
		if plan.Kind != cowgen.KindScalar || plan.FieldName != "Level" {
			continue
		}
		fmt.Fprintf(b, "// PutLevelV2 写 Hero.Level 并记录结构化 Undo。\n")
		fmt.Fprintf(b, "func (%s *Hero) PutLevelV2(ctx *TxContextV2, val %s) {\n", r, plan.LeafType)
		fmt.Fprintf(b, "\told := %s.%s\n", r, plan.FieldName)
		fmt.Fprintf(b, "\tif old == val {\n\t\treturn\n\t}\n")
		fmt.Fprintf(b, "\tctx.push(undoOpV2{\n")
		fmt.Fprintf(b, "\t\tkind:   undoKindHeroLevelV2,\n")
		fmt.Fprintf(b, "\t\thero:   %s,\n", r)
		fmt.Fprintf(b, "\t\toldI32: old,\n")
		fmt.Fprintf(b, "\t})\n")
		fmt.Fprintf(b, "\t%s.%s = val\n", r, plan.FieldName)
		fmt.Fprintf(b, "}\n\n")
	}
}

func emitPlayerMethodsV2(b *bytes.Buffer, sp *cowgen.StructPlan) {
	for _, plan := range sp.Plans {
		switch plan.FieldName {
		case "Assets":
			emitPlayerAssetsV2(b, plan)
		case "Items":
			emitPlayerItemsV2(b, plan)
		case "Bags":
			emitPlayerMapSliceV2(b, plan, mapSliceCfgV2{
				mapField:     "p.Bags",
				ensureKind:   "undoKindPlayerBagsEnsureNilV2",
				appendKind:   "undoKindPlayerBagsAppendAtKeyV2",
				setKind:      "undoKindPlayerBagsSetAtKeyV2",
				oldFieldName: "bagOld",
				label:        "map[k][]*Item",
			})
		case "Stats":
			emitPlayerStatsV2(b, plan)
		case "Cooldowns":
			emitPlayerMapSliceV2(b, plan, mapSliceCfgV2{
				mapField:     "p.Cooldowns",
				ensureKind:   "undoKindPlayerCooldownsEnsureNilV2",
				appendKind:   "",
				setKind:      "undoKindPlayerCooldownsSetAtKeyV2",
				oldFieldName: "cdOld",
				label:        "map[k][]int32",
			})
		case "Heros":
			emitPlayerHerosV2(b, plan)
		case "MainHero":
			emitPlayerMainHeroV2(b, plan)
		}
	}
}
