package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strings"
)

func mapTypeString(plan FieldPlan) string {
	if plan.SliceType != "" && len(plan.Keys) >= 1 {
		return "map[" + plan.Keys[0].KeyType + "]" + plan.SliceType
	}
	if len(plan.Keys) == 2 && plan.MapValue != "" {
		return "map[" + plan.Keys[0].KeyType + "]" + plan.MapValue
	}
	if len(plan.Keys) == 1 && plan.LeafType != "" {
		return "map[" + plan.Keys[0].KeyType + "]" + plan.LeafType
	}
	return ""
}

func emit(output, pkgName string, g *Graph) error {
	var b bytes.Buffer
	b.WriteString("// Code generated by undoproxy-gen. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", pkgName))
	for _, sp := range g.Structs {
		emitClone(&b, sp)
		for _, plan := range sp.Plans {
			emitMethods(&b, sp.Name, plan)
		}
	}
	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("format: %w", err)
	}
	return os.WriteFile(output, formatted, 0o644)
}

func emitClone(b *bytes.Buffer, sp *StructPlan) {
	r := recvIdent(sp.Name)
	fmt.Fprintf(b, "func (%s *%s) CloneForWrite() *%s {\n", r, sp.Name, sp.Name)
	fmt.Fprintf(b, "\tif %s == nil {\n\t\treturn nil\n\t}\n", r)
	fmt.Fprintf(b, "\treturn &%s{\n", sp.Name)
	st := sp.Struct
	if st != nil {
		for i := 0; i < st.NumFields(); i++ {
			f := st.Field(i)
			if !f.Exported() {
				continue
			}
			fmt.Fprintf(b, "\t\t%s: %s.%s,\n", f.Name(), r, f.Name())
		}
	}
	b.WriteString("\t}\n}\n\n")
}

func emitMethods(b *bytes.Buffer, structName string, plan FieldPlan) {
	r := recvIdent(structName)
	acc := r + "." + plan.FieldName
	switch plan.Kind {
	case KindScalar:
		emitScalarPut(b, structName, r, acc, plan)
	case KindPtrStruct:
		emitPtrGetForWrite(b, structName, r, acc, plan.FieldName, plan.LeafType)
	case KindMapScalar, KindMapStruct:
		emitMapPut(b, structName, r, acc, plan, false)
	case KindMapPtrStruct:
		emitMapPtrGet(b, structName, r, acc, plan)
		emitMapPut(b, structName, r, acc, plan, true)
	case KindSliceValue, KindSlicePtr:
		emitSliceOps(b, structName, r, acc, plan, "")
	case KindMapSliceValue, KindMapSlicePtr:
		emitMapSliceOps(b, structName, r, acc, plan)
	case KindMapMapScalar, KindMapMapStruct:
		emitMapMapPut(b, structName, r, acc, plan, false)
		emitMapMapGetForWrite(b, structName, r, acc, plan)
	case KindMapMapPtrStruct:
		emitMapMapPtrGet(b, structName, r, acc, plan)
		emitMapMapPut(b, structName, r, acc, plan, true)
		emitMapMapGetForWrite(b, structName, r, acc, plan)
	case KindMapMapSliceValue, KindMapMapSlicePtr:
		emitMapMapSliceOps(b, structName, r, acc, plan)
	}
}

func emitScalarPut(b *bytes.Buffer, structName, r, acc string, plan FieldPlan) {
	fmt.Fprintf(b, "func (%s *%s) Put%s(ctx *TxContext, val %s) {\n", r, structName, plan.FieldName, plan.LeafType)
	fmt.Fprintf(b, "\told := %s\n", acc)
	fmt.Fprintf(b, "\tctx.AddUndo(func() { %s = old })\n", acc)
	fmt.Fprintf(b, "\t%s = val\n}\n\n", acc)
}

func emitPtrGetForWrite(b *bytes.Buffer, structName, r, acc, field, typ string) {
	fmt.Fprintf(b, "func (%s *%s) Get%sForWrite(ctx *TxContext) %s {\n", r, structName, field, typ)
	fmt.Fprintf(b, "\told := %s\n", acc)
	fmt.Fprintf(b, "\tif old == nil {\n\t\treturn nil\n\t}\n")
	fmt.Fprintf(b, "\tdirty := old.CloneForWrite()\n")
	fmt.Fprintf(b, "\tctx.AddUndo(func() { %s = old })\n", acc)
	fmt.Fprintf(b, "\t%s = dirty\n", acc)
	fmt.Fprintf(b, "\treturn dirty\n}\n\n")
}

func emitMapEnsure(b *bytes.Buffer, r, acc, mapType string) {
	fmt.Fprintf(b, "\tif %s == nil {\n", acc)
	fmt.Fprintf(b, "\t\tctx.AddUndo(func() { %s = nil })\n", acc)
	fmt.Fprintf(b, "\t\t%s = make(%s)\n", acc, mapType)
	fmt.Fprintf(b, "\t}\n")
}

func emitMapPut(b *bytes.Buffer, structName, r, acc string, plan FieldPlan, ptrClone bool) {
	kp := keyParams(plan.Keys)
	ka := keyArgs(plan.Keys)
	valType := plan.LeafType
	if plan.Kind == KindMapStruct {
		valType = strings.TrimPrefix(valType, "*")
	}
	fmt.Fprintf(b, "func (%s *%s) Put%s(ctx *TxContext, %s, val %s) {\n", r, structName, plan.FieldName, kp, valType)
	emitMapEnsure(b, r, acc, "map["+plan.Keys[0].KeyType+"]"+valueTypeForMap(plan))
	fmt.Fprintf(b, "\told, existed := %s[%s]\n", acc, ka)
	if ptrClone {
		fmt.Fprintf(b, "\tif val != nil {\n\t\tval = val.CloneForWrite()\n\t}\n")
	}
	fmt.Fprintf(b, "\t%s[%s] = val\n", acc, ka)
	fmt.Fprintf(b, "\tctx.AddUndo(func() {\n")
	fmt.Fprintf(b, "\t\tif existed {\n\t\t\t%s[%s] = old\n", acc, ka)
	fmt.Fprintf(b, "\t\t} else {\n\t\t\tdelete(%s, %s)\n", acc, ka)
	fmt.Fprintf(b, "\t\t}\n\t})\n}\n\n")
}

func valueTypeForMap(plan FieldPlan) string {
	switch plan.Kind {
	case KindMapScalar:
		return plan.LeafType
	case KindMapStruct:
		return plan.LeafType
	case KindMapPtrStruct:
		return plan.LeafType
	default:
		return plan.LeafType
	}
}

func emitMapPtrGet(b *bytes.Buffer, structName, r, acc string, plan FieldPlan) {
	ka := keyArgs(plan.Keys)
	ret := plan.LeafType
	fmt.Fprintf(b, "func (%s *%s) Get%sForWrite(ctx *TxContext, %s) %s {\n",
		r, structName, plan.ElemName, keyParams(plan.Keys), ret)
	emitMapEnsure(b, r, acc, mapTypeFromPlan(plan))
	fmt.Fprintf(b, "\told, ok := %s[%s]\n", acc, ka)
	fmt.Fprintf(b, "\tif !ok || old == nil {\n\t\treturn nil\n\t}\n")
	fmt.Fprintf(b, "\tdirty := old.CloneForWrite()\n")
	fmt.Fprintf(b, "\tctx.AddUndo(func() { %s[%s] = old })\n", acc, ka)
	fmt.Fprintf(b, "\t%s[%s] = dirty\n", acc, ka)
	fmt.Fprintf(b, "\treturn dirty\n}\n\n")
}

func mapTypeFromPlan(plan FieldPlan) string {
	if len(plan.Keys) == 1 {
		return "map[" + plan.Keys[0].KeyType + "]" + plan.LeafType
	}
	return "map[" + plan.Keys[0].KeyType + "]" + plan.MapValue
}

func emitSliceOps(b *bytes.Buffer, structName, r, acc string, plan FieldPlan, keyPrefix string) {
	names := sliceMethodNames(plan.FieldName)
	elem := plan.SliceElem
	if keyPrefix != "" {
		emitMapSliceAppend(b, structName, r, acc, plan, names, elem, keyPrefix)
		emitMapSliceSet(b, structName, r, acc, plan, names, elem, keyPrefix)
		emitMapSliceRemove(b, structName, r, acc, plan, names, elem, keyPrefix)
		emitMapSliceTruncate(b, structName, r, acc, plan, names, keyPrefix)
		if plan.Kind == KindMapSlicePtr || plan.Kind == KindMapMapSlicePtr {
			emitMapSliceElemGet(b, structName, r, acc, plan, keyPrefix)
		}
		return
	}
	// 字段级 slice
	fmt.Fprintf(b, "func (%s *%s) %s(ctx *TxContext, elem %s) {\n", r, structName, names.Append, elem)
	fmt.Fprintf(b, "\toldLen := len(%s)\n", acc)
	fmt.Fprintf(b, "\t%s = append(%s, elem)\n", acc, acc)
	fmt.Fprintf(b, "\tctx.AddUndo(func() { %s = %s[:oldLen] })\n}\n\n", acc, acc)

	fmt.Fprintf(b, "func (%s *%s) %s(ctx *TxContext, i int, elem %s) {\n", r, structName, names.SetAt, elem)
	fmt.Fprintf(b, "\told := %s[i]\n", acc)
	fmt.Fprintf(b, "\tctx.AddUndo(func() { %s[i] = old })\n", acc)
	fmt.Fprintf(b, "\t%s[i] = elem\n}\n\n", acc)

	fmt.Fprintf(b, "func (%s *%s) %s(ctx *TxContext, i int) {\n", r, structName, names.RemoveAt)
	fmt.Fprintf(b, "\told := %s[i]\n", acc)
	fmt.Fprintf(b, "\t%s = append(%s[:i], %s[i+1:]...)\n", acc, acc, acc)
	fmt.Fprintf(b, "\tctx.AddUndo(func() { %s = append(%s[:i], append([]%s{old}, %s[i:]...)...) })\n}\n\n",
		acc, acc, elem, acc)

	fmt.Fprintf(b, "func (%s *%s) %s(ctx *TxContext, n int) {\n", r, structName, names.Truncate)
	fmt.Fprintf(b, "\tif n >= len(%s) {\n\t\treturn\n\t}\n", acc)
	fmt.Fprintf(b, "\ttail := append([]%s(nil), %s[n:]...)\n", elem, acc)
	fmt.Fprintf(b, "\t%s = %s[:n]\n", acc, acc)
	fmt.Fprintf(b, "\tctx.AddUndo(func() { %s = append(%s, tail...) })\n}\n\n", acc, acc)
}

func emitMapSliceOps(b *bytes.Buffer, structName, r, acc string, plan FieldPlan) {
	kp := keyParams(plan.Keys)
	emitSliceOps(b, structName, r, acc, plan, kp)
	fmt.Fprintf(b, "func (%s *%s) Put%s(ctx *TxContext, %s, val %s) {\n",
		r, structName, plan.FieldName, kp, plan.SliceType)
	emitMapEnsure(b, r, acc, mapTypeString(plan))
	ka := keyArgs(plan.Keys)
	fmt.Fprintf(b, "\told, existed := %s[%s]\n", acc, ka)
	fmt.Fprintf(b, "\t%s[%s] = val\n", acc, ka)
	fmt.Fprintf(b, "\tctx.AddUndo(func() {\n")
	fmt.Fprintf(b, "\t\tif existed {\n\t\t\t%s[%s] = old\n", acc, ka)
	fmt.Fprintf(b, "\t\t} else {\n\t\t\tdelete(%s, %s)\n", acc, ka)
	fmt.Fprintf(b, "\t\t}\n\t})\n}\n\n")
}

func emitMapSliceAppend(b *bytes.Buffer, structName, r, acc string, plan FieldPlan, names sliceMethods, elem, kp string) {
	ka := keyArgs(plan.Keys)
	fmt.Fprintf(b, "func (%s *%s) %s(ctx *TxContext, %s, elem %s) {\n", r, structName, names.Append+"At", kp, elem)
	emitMapEnsure(b, r, acc, mapTypeString(plan))
	fmt.Fprintf(b, "\tprev, existed := %s[%s]\n", acc, ka)
	fmt.Fprintf(b, "\toldLen := len(prev)\n")
	fmt.Fprintf(b, "\t%s[%s] = append(prev, elem)\n", acc, ka)
	fmt.Fprintf(b, "\tctx.AddUndo(func() {\n")
	fmt.Fprintf(b, "\t\tif !existed {\n\t\t\tdelete(%s, %s)\n", acc, ka)
	fmt.Fprintf(b, "\t\t} else {\n\t\t\t%s[%s] = prev[:oldLen]\n", acc, ka)
	fmt.Fprintf(b, "\t\t}\n\t})\n}\n\n")
}

func emitMapSliceSet(b *bytes.Buffer, structName, r, acc string, plan FieldPlan, names sliceMethods, elem, kp string) {
	ka := keyArgs(plan.Keys)
	fmt.Fprintf(b, "func (%s *%s) %s(ctx *TxContext, %s, i int, elem %s) {\n", r, structName, names.SetAt, kp, elem)
	emitMapEnsure(b, r, acc, mapTypeString(plan))
	fmt.Fprintf(b, "\told := %s[%s][i]\n", acc, ka)
	fmt.Fprintf(b, "\tctx.AddUndo(func() { %s[%s][i] = old })\n", acc, ka)
	fmt.Fprintf(b, "\t%s[%s][i] = elem\n}\n\n", acc, ka)
}

func emitMapSliceRemove(b *bytes.Buffer, structName, r, acc string, plan FieldPlan, names sliceMethods, elem, kp string) {
	ka := keyArgs(plan.Keys)
	fmt.Fprintf(b, "func (%s *%s) %s(ctx *TxContext, %s, i int) {\n", r, structName, names.RemoveAt, kp)
	emitMapEnsure(b, r, acc, mapTypeString(plan))
	fmt.Fprintf(b, "\ts := %s[%s]\n", acc, ka)
	fmt.Fprintf(b, "\told := s[i]\n")
	fmt.Fprintf(b, "\t%s[%s] = append(s[:i], s[i+1:]...)\n", acc, ka)
	fmt.Fprintf(b, "\tctx.AddUndo(func() { %s[%s] = append(%s[%s][:i], append([]%s{old}, %s[%s][i:]...)...) })\n}\n\n",
		acc, ka, acc, ka, elem, acc, ka)
}

func emitMapSliceTruncate(b *bytes.Buffer, structName, r, acc string, plan FieldPlan, names sliceMethods, kp string) {
	ka := keyArgs(plan.Keys)
	elem := plan.SliceElem
	fmt.Fprintf(b, "func (%s *%s) %s(ctx *TxContext, %s, n int) {\n", r, structName, names.Truncate, kp)
	emitMapEnsure(b, r, acc, mapTypeString(plan))
	fmt.Fprintf(b, "\ts := %s[%s]\n", acc, ka)
	fmt.Fprintf(b, "\tif n >= len(s) {\n\t\treturn\n\t}\n")
	fmt.Fprintf(b, "\ttail := append([]%s(nil), s[n:]...)\n", elem)
	fmt.Fprintf(b, "\t%s[%s] = s[:n]\n", acc, ka)
	fmt.Fprintf(b, "\tctx.AddUndo(func() { %s[%s] = append(%s[%s], tail...) })\n}\n\n", acc, ka, acc, ka)
}

func emitMapSliceElemGet(b *bytes.Buffer, structName, r, acc string, plan FieldPlan, kp string) {
	ka := keyArgs(plan.Keys)
	en := plan.ElemName
	if en == "" {
		en = singular(plan.FieldName)
	}
	fmt.Fprintf(b, "func (%s *%s) %s(ctx *TxContext, %s, i int) %s {\n",
		r, structName, elemAtForWriteName(en), kp, plan.SliceElem)
	emitMapEnsure(b, r, acc, mapTypeString(plan))
	fmt.Fprintf(b, "\told := %s[%s][i]\n", acc, ka)
	fmt.Fprintf(b, "\tif old == nil {\n\t\treturn nil\n\t}\n")
	fmt.Fprintf(b, "\tdirty := old.CloneForWrite()\n")
	fmt.Fprintf(b, "\tctx.AddUndo(func() { %s[%s][i] = old })\n", acc, ka)
	fmt.Fprintf(b, "\t%s[%s][i] = dirty\n", acc, ka)
	fmt.Fprintf(b, "\treturn dirty\n}\n\n")
}

func emitMapMapPut(b *bytes.Buffer, structName, r, acc string, plan FieldPlan, ptrClone bool) {
	kp := keyParams(plan.Keys)
	valType := plan.LeafType
	innerVal := innerValueType(plan)
	fmt.Fprintf(b, "func (%s *%s) Put%s(ctx *TxContext, %s, val %s) {\n", r, structName, plan.FieldName, kp, valType)
	emitMapEnsure(b, r, acc, "map["+plan.Keys[0].KeyType+"]"+plan.MapValue)
	fmt.Fprintf(b, "\tinner, ok := %s[k1]\n", acc)
	fmt.Fprintf(b, "\tif !ok || inner == nil {\n")
	fmt.Fprintf(b, "\t\tctx.AddUndo(func() { delete(%s, k1) })\n", acc)
	fmt.Fprintf(b, "\t\tinner = make(map[%s]%s)\n", plan.Keys[1].KeyType, innerVal)
	fmt.Fprintf(b, "\t\t%s[k1] = inner\n", acc)
	fmt.Fprintf(b, "\t}\n")
	fmt.Fprintf(b, "\told, existed := inner[k2]\n")
	if ptrClone {
		fmt.Fprintf(b, "\tif val != nil {\n\t\tval = val.CloneForWrite()\n\t}\n")
	}
	fmt.Fprintf(b, "\tinner[k2] = val\n")
	fmt.Fprintf(b, "\tctx.AddUndo(func() {\n")
	fmt.Fprintf(b, "\t\tif existed {\n\t\t\tinner[k2] = old\n")
	fmt.Fprintf(b, "\t\t} else {\n\t\t\tdelete(inner, k2)\n")
	fmt.Fprintf(b, "\t\t}\n\t})\n}\n\n")
}

func innerValueType(plan FieldPlan) string {
	return plan.LeafType
}

func emitMapMapGetForWrite(b *bytes.Buffer, structName, r, acc string, plan FieldPlan) {
	kp := keyParams([]KeyLayer{plan.Keys[0]})
	fmt.Fprintf(b, "func (%s *%s) %s(ctx *TxContext, %s) map[%s]%s {\n",
		r, structName, mapForWriteName(plan.FieldName), kp,
		plan.Keys[1].KeyType, innerValueType(plan))
	emitMapEnsure(b, r, acc, "map["+plan.Keys[0].KeyType+"]"+plan.MapValue)
	fmt.Fprintf(b, "\toldInner, existed := %s[k1]\n", acc)
	fmt.Fprintf(b, "\tif !existed || oldInner == nil {\n")
	fmt.Fprintf(b, "\t\tnewInner := make(map[%s]%s)\n", plan.Keys[1].KeyType, innerValueType(plan))
	fmt.Fprintf(b, "\t\tctx.AddUndo(func() {\n")
	fmt.Fprintf(b, "\t\t\tif !existed {\n\t\t\t\tdelete(%s, k1)\n", acc)
	fmt.Fprintf(b, "\t\t\t} else {\n\t\t\t\t%s[k1] = oldInner\n", acc)
	fmt.Fprintf(b, "\t\t\t}\n\t\t})\n")
	fmt.Fprintf(b, "\t\t%s[k1] = newInner\n", acc)
	fmt.Fprintf(b, "\t\treturn newInner\n\t}\n")
	fmt.Fprintf(b, "\tdirty := clone%sMapShallow(oldInner)\n", plan.FieldName)
	fmt.Fprintf(b, "\tctx.AddUndo(func() { %s[k1] = oldInner })\n", acc)
	fmt.Fprintf(b, "\t%s[k1] = dirty\n", acc)
	fmt.Fprintf(b, "\treturn dirty\n}\n\n")
	emitCloneMapShallow(b, plan)
}

func emitCloneMapShallow(b *bytes.Buffer, plan FieldPlan) {
	fmt.Fprintf(b, "func clone%sMapShallow(m map[%s]%s) map[%s]%s {\n",
		plan.FieldName, plan.Keys[1].KeyType, innerValueType(plan),
		plan.Keys[1].KeyType, innerValueType(plan))
	fmt.Fprintf(b, "\tif m == nil {\n\t\treturn nil\n\t}\n")
	fmt.Fprintf(b, "\tc := make(map[%s]%s, len(m))\n", plan.Keys[1].KeyType, innerValueType(plan))
	fmt.Fprintf(b, "\tfor k, v := range m {\n\t\tc[k] = v\n\t}\n")
	fmt.Fprintf(b, "\treturn c\n}\n\n")
}

func emitMapMapPtrGet(b *bytes.Buffer, structName, r, acc string, plan FieldPlan) {
	ka := keyParams(plan.Keys)
	fmt.Fprintf(b, "func (%s *%s) Get%sForWrite(ctx *TxContext, %s) %s {\n",
		r, structName, plan.ElemName, ka, plan.LeafType)
	emitMapEnsure(b, r, acc, "map["+plan.Keys[0].KeyType+"]"+plan.MapValue)
	fmt.Fprintf(b, "\tinner := %s[k1]\n", acc)
	fmt.Fprintf(b, "\tif inner == nil {\n\t\treturn nil\n\t}\n")
	fmt.Fprintf(b, "\told, ok := inner[k2]\n")
	fmt.Fprintf(b, "\tif !ok || old == nil {\n\t\treturn nil\n\t}\n")
	fmt.Fprintf(b, "\tdirty := old.CloneForWrite()\n")
	fmt.Fprintf(b, "\tctx.AddUndo(func() { inner[k2] = old })\n")
	fmt.Fprintf(b, "\tinner[k2] = dirty\n")
	fmt.Fprintf(b, "\treturn dirty\n}\n\n")
}

func emitMapMapSliceOps(b *bytes.Buffer, structName, r, acc string, plan FieldPlan) {
	kp := keyParams(plan.Keys)
	names := sliceMethodNames(plan.FieldName)
	elem := plan.SliceElem
	emitMapMapSliceAppend(b, structName, r, acc, plan, names, elem, kp)
	emitMapMapSliceSet(b, structName, r, acc, plan, names, elem, kp)
	emitMapMapSliceRemove(b, structName, r, acc, plan, names, elem, kp)
	emitMapMapSliceTruncate(b, structName, r, acc, plan, names, kp)
	fmt.Fprintf(b, "func (%s *%s) Put%s(ctx *TxContext, %s, val %s) {\n",
		r, structName, plan.FieldName, kp, plan.SliceType)
	emitMapEnsure(b, r, acc, "map["+plan.Keys[0].KeyType+"]"+plan.MapValue)
	fmt.Fprintf(b, "\tinner, ok := %s[k1]\n", acc)
	fmt.Fprintf(b, "\tif !ok || inner == nil {\n")
	fmt.Fprintf(b, "\t\tctx.AddUndo(func() { delete(%s, k1) })\n", acc)
	fmt.Fprintf(b, "\t\tinner = make(map[%s]%s)\n", plan.Keys[1].KeyType, plan.SliceType)
	fmt.Fprintf(b, "\t\t%s[k1] = inner\n", acc)
	fmt.Fprintf(b, "\t}\n")
	fmt.Fprintf(b, "\told, existed := inner[k2]\n")
	fmt.Fprintf(b, "\tinner[k2] = val\n")
	fmt.Fprintf(b, "\tctx.AddUndo(func() {\n")
	fmt.Fprintf(b, "\t\tif existed {\n\t\t\tinner[k2] = old\n")
	fmt.Fprintf(b, "\t\t} else {\n\t\t\tdelete(inner, k2)\n")
	fmt.Fprintf(b, "\t\t}\n\t})\n}\n\n")
}

func emitMapMapSliceAppend(b *bytes.Buffer, structName, r, acc string, plan FieldPlan, names sliceMethods, elem, kp string) {
	fmt.Fprintf(b, "func (%s *%s) %s(ctx *TxContext, %s, elem %s) {\n", r, structName, names.Append+"At", kp, elem)
	emitMapEnsure(b, r, acc, "map["+plan.Keys[0].KeyType+"]"+plan.MapValue)
	fmt.Fprintf(b, "\tinner := %s[k1]\n", acc)
	fmt.Fprintf(b, "\tif inner == nil {\n")
	fmt.Fprintf(b, "\t\tctx.AddUndo(func() { delete(%s, k1) })\n", acc)
	fmt.Fprintf(b, "\t\tinner = make(map[%s]%s)\n", plan.Keys[1].KeyType, plan.SliceType)
	fmt.Fprintf(b, "\t\t%s[k1] = inner\n", acc)
	fmt.Fprintf(b, "\t}\n")
	fmt.Fprintf(b, "\tprev, existed := inner[k2]\n")
	fmt.Fprintf(b, "\toldLen := len(prev)\n")
	fmt.Fprintf(b, "\tinner[k2] = append(prev, elem)\n")
	fmt.Fprintf(b, "\tctx.AddUndo(func() {\n")
	fmt.Fprintf(b, "\t\tif !existed {\n\t\t\tdelete(inner, k2)\n")
	fmt.Fprintf(b, "\t\t} else {\n\t\t\tinner[k2] = prev[:oldLen]\n")
	fmt.Fprintf(b, "\t\t}\n\t})\n}\n\n")
}

func emitMapMapSliceSet(b *bytes.Buffer, structName, r, acc string, plan FieldPlan, names sliceMethods, elem, kp string) {
	fmt.Fprintf(b, "func (%s *%s) %s(ctx *TxContext, %s, i int, elem %s) {\n", r, structName, names.SetAt, kp, elem)
	emitMapEnsure(b, r, acc, "map["+plan.Keys[0].KeyType+"]"+plan.MapValue)
	fmt.Fprintf(b, "\tinner := %s[k1]\n", acc)
	fmt.Fprintf(b, "\told := inner[k2][i]\n")
	fmt.Fprintf(b, "\tctx.AddUndo(func() { inner[k2][i] = old })\n")
	fmt.Fprintf(b, "\tinner[k2][i] = elem\n}\n\n")
}

func emitMapMapSliceRemove(b *bytes.Buffer, structName, r, acc string, plan FieldPlan, names sliceMethods, elem, kp string) {
	fmt.Fprintf(b, "func (%s *%s) %s(ctx *TxContext, %s, i int) {\n", r, structName, names.RemoveAt, kp)
	emitMapEnsure(b, r, acc, "map["+plan.Keys[0].KeyType+"]"+plan.MapValue)
	fmt.Fprintf(b, "\tinner := %s[k1]\n", acc)
	fmt.Fprintf(b, "\ts := inner[k2]\n")
	fmt.Fprintf(b, "\told := s[i]\n")
	fmt.Fprintf(b, "\tinner[k2] = append(s[:i], s[i+1:]...)\n")
	fmt.Fprintf(b, "\tctx.AddUndo(func() { inner[k2] = append(inner[k2][:i], append([]%s{old}, inner[k2][i:]...)...) })\n}\n\n", elem)
}

func emitMapMapSliceTruncate(b *bytes.Buffer, structName, r, acc string, plan FieldPlan, names sliceMethods, kp string) {
	elem := plan.SliceElem
	fmt.Fprintf(b, "func (%s *%s) %s(ctx *TxContext, %s, n int) {\n", r, structName, names.Truncate, kp)
	emitMapEnsure(b, r, acc, "map["+plan.Keys[0].KeyType+"]"+plan.MapValue)
	fmt.Fprintf(b, "\tinner := %s[k1]\n", acc)
	fmt.Fprintf(b, "\ts := inner[k2]\n")
	fmt.Fprintf(b, "\tif n >= len(s) {\n\t\treturn\n\t}\n")
	fmt.Fprintf(b, "\ttail := append([]%s(nil), s[n:]...)\n", elem)
	fmt.Fprintf(b, "\tinner[k2] = s[:n]\n")
	fmt.Fprintf(b, "\tctx.AddUndo(func() { inner[k2] = append(inner[k2], tail...) })\n}\n\n")
}
