package main

import "bytes"

func emitV2Runtime(b *bytes.Buffer) {
	emitV2UndoKindAndOp(b)
	emitV2Context(b)
	emitV2Rollback(b)
	emitV2StatsClone(b)
}

func emitV2UndoKindAndOp(b *bytes.Buffer) {
	b.WriteString("type undoKindV2 uint8\n\n")
	b.WriteString("const (\n")
	b.WriteString("\tundoKindPlayerLevelV2 undoKindV2 = iota + 1\n")
	b.WriteString("\tundoKindPlayerAssetsEnsureNilV2\n")
	b.WriteString("\tundoKindPlayerAssetsSetV2\n")
	b.WriteString("\tundoKindPlayerItemsTruncateV2\n")
	b.WriteString("\tundoKindPlayerItemsSetV2\n")
	b.WriteString("\tundoKindPlayerBagsEnsureNilV2\n")
	b.WriteString("\tundoKindPlayerBagsAppendAtKeyV2\n")
	b.WriteString("\tundoKindPlayerBagsSetAtKeyV2\n")
	b.WriteString("\tundoKindPlayerStatsEnsureNilV2\n")
	b.WriteString("\tundoKindPlayerStatsPutAtKeyV2\n")
	b.WriteString("\tundoKindPlayerStatsSetAtKeyV2\n")
	b.WriteString("\tundoKindPlayerCooldownsEnsureNilV2\n")
	b.WriteString("\tundoKindPlayerCooldownsSetAtKeyV2\n")
	b.WriteString("\tundoKindPlayerHerosEnsureNilV2\n")
	b.WriteString("\tundoKindPlayerHerosSetAtKeyV2\n")
	b.WriteString("\tundoKindPlayerMainHeroSetV2\n")
	b.WriteString("\tundoKindHeroLevelV2\n")
	b.WriteString(")\n\n")

	b.WriteString("type undoOpV2 struct {\n")
	b.WriteString("\tkind undoKindV2\n\n")
	b.WriteString("\tplayer *Player\n")
	b.WriteString("\thero   *Hero\n\n")
	b.WriteString("\tkeyI32    int32\n")
	b.WriteString("\tkeyString string\n\n")
	b.WriteString("\toldI32 int32\n")
	b.WriteString("\toldI64 int64\n")
	b.WriteString("\toldInt int\n\n")
	b.WriteString("\ttail     []*Item\n")
	b.WriteString("\tbagOld   []*Item\n")
	b.WriteString("\tstatsOld map[string]int64\n")
	b.WriteString("\tcdOld    []int32\n\n")
	b.WriteString("\thad  bool\n")
	b.WriteString("\thad2 bool\n")
	b.WriteString("}\n\n")
}

func emitV2Context(b *bytes.Buffer) {
	b.WriteString("// TxContextV2 实验性 Undo 日志（单协程，无锁）。\n")
	b.WriteString("//\n")
	b.WriteString("// 目标：并行验证结构化日志是否降低闭包分配。\n")
	b.WriteString("//\n")
	b.WriteString("// +k8s:deepcopy-gen=false\n")
	b.WriteString("type TxContextV2 struct {\n")
	b.WriteString("\tops []undoOpV2\n")
	b.WriteString("}\n\n")

	b.WriteString("func (ctx *TxContextV2) push(op undoOpV2) {\n")
	b.WriteString("\tctx.ops = append(ctx.ops, op)\n")
	b.WriteString("}\n\n")

	b.WriteString("// Reset 清空日志并复用底层切片。\n")
	b.WriteString("func (ctx *TxContextV2) Reset() {\n")
	b.WriteString("\tfor i := range ctx.ops {\n")
	b.WriteString("\t\tctx.ops[i] = undoOpV2{}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tctx.ops = ctx.ops[:0]\n")
	b.WriteString("}\n\n")

	b.WriteString("var txPoolV2 = sync.Pool{\n")
	b.WriteString("\tNew: func() any {\n")
	b.WriteString("\t\treturn &TxContextV2{ops: make([]undoOpV2, 0, 16)}\n")
	b.WriteString("\t},\n")
	b.WriteString("}\n\n")
}

func emitV2Rollback(b *bytes.Buffer) {
	b.WriteString("// Rollback 倒序执行所有逆操作。\n")
	b.WriteString("func (ctx *TxContextV2) Rollback() {\n")
	b.WriteString("\tfor i := len(ctx.ops) - 1; i >= 0; i-- {\n")
	b.WriteString("\t\top := ctx.ops[i]\n")
	b.WriteString("\t\tswitch op.kind {\n")
	b.WriteString("\t\tcase undoKindPlayerLevelV2:\n")
	b.WriteString("\t\t\top.player.Level = op.oldI32\n")
	b.WriteString("\t\tcase undoKindPlayerAssetsEnsureNilV2:\n")
	b.WriteString("\t\t\top.player.Assets = nil\n")
	b.WriteString("\t\tcase undoKindPlayerAssetsSetV2:\n")
	b.WriteString("\t\t\tif op.had {\n")
	b.WriteString("\t\t\t\top.player.Assets[op.keyString] = op.oldI64\n")
	b.WriteString("\t\t\t} else {\n")
	b.WriteString("\t\t\t\tdelete(op.player.Assets, op.keyString)\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\tcase undoKindPlayerItemsTruncateV2:\n")
	b.WriteString("\t\t\top.player.Items = op.player.Items[:op.oldInt]\n")
	b.WriteString("\t\tcase undoKindPlayerItemsSetV2:\n")
	b.WriteString("\t\t\top.player.Items = append([]*Item(nil), op.tail...)\n")
	b.WriteString("\t\tcase undoKindPlayerBagsEnsureNilV2:\n")
	b.WriteString("\t\t\top.player.Bags = nil\n")
	b.WriteString("\t\tcase undoKindPlayerBagsAppendAtKeyV2:\n")
	b.WriteString("\t\t\tif op.had {\n")
	b.WriteString("\t\t\t\top.player.Bags[op.keyI32] = op.bagOld[:op.oldInt]\n")
	b.WriteString("\t\t\t} else {\n")
	b.WriteString("\t\t\t\tdelete(op.player.Bags, op.keyI32)\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\tcase undoKindPlayerBagsSetAtKeyV2:\n")
	b.WriteString("\t\t\tif op.had {\n")
	b.WriteString("\t\t\t\top.player.Bags[op.keyI32] = append([]*Item(nil), op.bagOld...)\n")
	b.WriteString("\t\t\t} else {\n")
	b.WriteString("\t\t\t\tdelete(op.player.Bags, op.keyI32)\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\tcase undoKindPlayerStatsEnsureNilV2:\n")
	b.WriteString("\t\t\top.player.Stats = nil\n")
	b.WriteString("\t\tcase undoKindPlayerStatsPutAtKeyV2:\n")
	b.WriteString("\t\t\tinner := op.player.Stats[op.keyI32]\n")
	b.WriteString("\t\t\tif op.had {\n")
	b.WriteString("\t\t\t\tinner[op.keyString] = op.oldI64\n")
	b.WriteString("\t\t\t} else {\n")
	b.WriteString("\t\t\t\tdelete(inner, op.keyString)\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\tif op.had2 {\n")
	b.WriteString("\t\t\t\tdelete(op.player.Stats, op.keyI32)\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\tcase undoKindPlayerStatsSetAtKeyV2:\n")
	b.WriteString("\t\t\tif op.had {\n")
	b.WriteString("\t\t\t\top.player.Stats[op.keyI32] = cloneStatsMapShallowV2(op.statsOld)\n")
	b.WriteString("\t\t\t} else {\n")
	b.WriteString("\t\t\t\tdelete(op.player.Stats, op.keyI32)\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\tcase undoKindPlayerCooldownsEnsureNilV2:\n")
	b.WriteString("\t\t\top.player.Cooldowns = nil\n")
	b.WriteString("\t\tcase undoKindPlayerCooldownsSetAtKeyV2:\n")
	b.WriteString("\t\t\tif op.had {\n")
	b.WriteString("\t\t\t\top.player.Cooldowns[op.keyI32] = append([]int32(nil), op.cdOld...)\n")
	b.WriteString("\t\t\t} else {\n")
	b.WriteString("\t\t\t\tdelete(op.player.Cooldowns, op.keyI32)\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\tcase undoKindPlayerHerosEnsureNilV2:\n")
	b.WriteString("\t\t\top.player.Heros = nil\n")
	b.WriteString("\t\tcase undoKindPlayerHerosSetAtKeyV2:\n")
	b.WriteString("\t\t\tif op.had {\n")
	b.WriteString("\t\t\t\top.player.Heros[op.keyI32] = op.hero\n")
	b.WriteString("\t\t\t} else {\n")
	b.WriteString("\t\t\t\tdelete(op.player.Heros, op.keyI32)\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\tcase undoKindPlayerMainHeroSetV2:\n")
	b.WriteString("\t\t\top.player.MainHero = op.hero\n")
	b.WriteString("\t\tcase undoKindHeroLevelV2:\n")
	b.WriteString("\t\t\top.hero.Level = op.oldI32\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")
}

func emitV2StatsClone(b *bytes.Buffer) {
	b.WriteString("func cloneStatsMapShallowV2(m map[string]int64) map[string]int64 {\n")
	b.WriteString("\tif m == nil {\n")
	b.WriteString("\t\treturn nil\n")
	b.WriteString("\t}\n")
	b.WriteString("\tout := make(map[string]int64, len(m))\n")
	b.WriteString("\tfor k, v := range m {\n")
	b.WriteString("\t\tout[k] = v\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn out\n")
	b.WriteString("}\n\n")
}
