package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"

	"github.com/huangyuCN/cow/internal/cowgen"
)

func emitFromGraph(output, pkgName string, g *cowgen.Graph) error {
	ub := newUndoBuilder(g)
	var methods bytes.Buffer
	for _, sp := range g.Structs {
		emitClone(&methods, sp)
		for _, plan := range sp.Plans {
			emitStructuredMethods(&methods, ub, sp.Name, plan)
		}
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by undoproxy-gen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkgName)
	writeImports(&b, g.Qualifiers)
	if err := ub.writeRuntime(&b); err != nil {
		return err
	}
	b.Write(methods.Bytes())
	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("format graph: %w", err)
	}
	return os.WriteFile(output, formatted, 0o644)
}

// writeImports 写出 sync 与 Qualifiers 登记的跨包 import。
func writeImports(b *bytes.Buffer, q *cowgen.Qualifiers) {
	b.WriteString("import (\n\t\"sync\"\n")
	if q != nil {
		imps := q.Imports()
		if len(imps) > 0 {
			b.WriteByte('\n')
			for _, im := range imps {
				fmt.Fprintf(b, "\t%s %q\n", im.Alias, im.Path)
			}
		}
	}
	b.WriteString(")\n\n")
}

func emitClone(b *bytes.Buffer, sp *cowgen.StructPlan) {
	r := cowgen.RecvIdent(sp.Name)
	fmt.Fprintf(b, "// CloneForWrite 返回 %s 的可写浅拷贝。\n", sp.Name)
	fmt.Fprintf(b, "func (%s *%s) CloneForWrite() *%s {\n", r, sp.Name, sp.Name)
	fmt.Fprintf(b, "\tif %s == nil {\n\t\treturn nil\n\t}\n", r)
	fmt.Fprintf(b, "\treturn &%s{\n", sp.Name)
	st := sp.Struct
	for i := 0; i < st.NumFields(); i++ {
		f := st.Field(i)
		if !f.Exported() {
			continue
		}
		fmt.Fprintf(b, "\t\t%s: %s.%s,\n", f.Name(), r, f.Name())
	}
	b.WriteString("\t}\n}\n\n")
}
